### PR TITLE
Just used to test the stability of TCK

### PR DESCRIPTION
**Pull request by bright-starry-sky**
Changed the tck case wait time from `heart_beat_interval` to `heart_beat_interval + 1`.
Please ignore the PR for a moment, I'm going to run the test repeatedly.

### CODE REVIEW

**Comment by bright-starry-sky** [comment]
`=================================== FAILURES ===================================
_______________________ test_v2ga_bug_negative_start_vid _______________________
[gw8] linux -- Python 3.8.10 /usr/bin/python3
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:177: in scenario_wrapper
    _execute_scenario(feature, scenario, request, encoding)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:143: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:113: in _execute_step_function
    return_value = step_func(**kwargs)
tck/conftest.py:243: in wait_job_to_finish
    assert is_finished, f"Fail to finish job {jid}"
E   AssertionError: Fail to finish job 128
E   assert False
----------------------------- Captured stderr call -----------------------------
[2021-09-13 10:14:24,734]:Get connection to ('127.0.0.1', 3020)
------------------------------ Captured log call -------------------------------
INFO     root:ConnectionPool.py:150 Get connection to ('127.0.0.1', 3020)
____________________ test_exists_with_dynamic_map_in_match _____________________
[gw2] linux -- Python 3.8.10 /usr/bin/python3
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:177: in scenario_wrapper
    _execute_scenario(feature, scenario, request, encoding)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:143: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:113: in _execute_step_function
    return_value = step_func(**kwargs)
tck/conftest.py:243: in wait_job_to_finish
    assert is_finished, f"Fail to finish job {jid}"
E   AssertionError: Fail to finish job 137
E   assert False
----------------------------- Captured stderr call -----------------------------
[2021-09-13 10:14:26,590]:Get connection to ('127.0.0.1', 3020)
------------------------------ Captured log call -------------------------------
INFO     root:ConnectionPool.py:150 Get connection to ('127.0.0.1', 3020)
_______________ test_indextest_intvid_rebuildtagindexstatusinfo ________________
[gw9] linux -- Python 3.8.10 /usr/bin/python3
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:177: in scenario_wrapper
    _execute_scenario(feature, scenario, request, encoding)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:143: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:113: in _execute_step_function
    return_value = step_func(**kwargs)
tck/conftest.py:243: in wait_job_to_finish
    assert is_finished, f"Fail to finish job {jid}"
E   AssertionError: Fail to finish job 153
E   assert False
----------------------------- Captured stderr call -----------------------------
[2021-09-13 10:14:43,558]:Get connection to ('127.0.0.1', 3020)
------------------------------ Captured log call -------------------------------
INFO     root:ConnectionPool.py:150 Get connection to ('127.0.0.1', 3020)
_______________ test_indextest_intvid_rebuildedgeindexstatusinfo _______________
[gw9] linux -- Python 3.8.10 /usr/bin/python3
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:177: in scenario_wrapper
    _execute_scenario(feature, scenario, request, encoding)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:143: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:113: in _execute_step_function
    return_value = step_func(**kwargs)
tck/conftest.py:243: in wait_job_to_finish
    assert is_finished, f"Fail to finish job {jid}"
E   AssertionError: Fail to finish job 173
E   assert False
----------------------------- Captured stderr call -----------------------------
[2021-09-13 10:14:57,252]:Get connection to ('127.0.0.1', 3020)
------------------------------ Captured log call -------------------------------
INFO     root:ConnectionPool.py:150 Get connection to ('127.0.0.1', 3020)
___________________ test_indextest_rebuildtagindexstatusinfo ___________________
[gw9] linux -- Python 3.8.10 /usr/bin/python3
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:177: in scenario_wrapper
    _execute_scenario(feature, scenario, request, encoding)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:143: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:113: in _execute_step_function
    return_value = step_func(**kwargs)
tck/conftest.py:243: in wait_job_to_finish
    assert is_finished, f"Fail to finish job {jid}"
E   AssertionError: Fail to finish job 260
E   assert False
----------------------------- Captured stderr call -----------------------------
[2021-09-13 10:15:52,660]:Get connection to ('127.0.0.1', 3020)
------------------------------ Captured log call -------------------------------
INFO     root:ConnectionPool.py:150 Get connection to ('127.0.0.1', 3020)
__________________ test_indextest_rebuildedgeindexstatusinfo ___________________
[gw9] linux -- Python 3.8.10 /usr/bin/python3
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:177: in scenario_wrapper
    _execute_scenario(feature, scenario, request, encoding)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:143: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:113: in _execute_step_function
    return_value = step_func(**kwargs)
tck/conftest.py:243: in wait_job_to_finish
    assert is_finished, f"Fail to finish job {jid}"
E   AssertionError: Fail to finish job 294
E   assert False
----------------------------- Captured stderr call -----------------------------
[2021-09-13 10:16:19,915]:Get connection to ('127.0.0.1', 3020)
------------------------------ Captured log call -------------------------------
INFO     root:ConnectionPool.py:150 Get connection to ('127.0.0.1', 3020)
_______________________ test_test_edge_index_from_pytest _______________________
[gw0] linux -- Python 3.8.10 /usr/bin/python3
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:177: in scenario_wrapper
    _execute_scenario(feature, scenario, request, encoding)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:143: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:113: in _execute_step_function
    return_value = step_func(**kwargs)
tck/conftest.py:243: in wait_job_to_finish
    assert is_finished, f"Fail to finish job {jid}"
E   AssertionError: Fail to finish job 295
E   assert False
----------------------------- Captured stderr call -----------------------------
[2021-09-13 10:16:20,944]:Get connection to ('127.0.0.1', 3020)
------------------------------ Captured log call -------------------------------
INFO     root:ConnectionPool.py:150 Get connection to ('127.0.0.1', 3020)
_______________________ test_test_tag_index_from_pytest ________________________
[gw4] linux -- Python 3.8.10 /usr/bin/python3
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:177: in scenario_wrapper
    _execute_scenario(feature, scenario, request, encoding)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:143: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:113: in _execute_step_function
    return_value = step_func(**kwargs)
tck/conftest.py:243: in wait_job_to_finish
    assert is_finished, f"Fail to finish job {jid}"
E   AssertionError: Fail to finish job 299
E   assert False
----------------------------- Captured stderr call -----------------------------
[2021-09-13 10:16:22,502]:Get connection to ('127.0.0.1', 3020)
------------------------------ Captured log call -------------------------------
INFO     root:ConnectionPool.py:150 Get connection to ('127.0.0.1', 3020)
____________ test_indextest_rebuild_all_tag_indexes_by_empty_input _____________
[gw9] linux -- Python 3.8.10 /usr/bin/python3
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:177: in scenario_wrapper
    _execute_scenario(feature, scenario, request, encoding)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:143: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:113: in _execute_step_function
    return_value = step_func(**kwargs)
tck/conftest.py:243: in wait_job_to_finish
    assert is_finished, f"Fail to finish job {jid}"
E   AssertionError: Fail to finish job 314
E   assert False
----------------------------- Captured stderr call -----------------------------
[2021-09-13 10:17:01,309]:Get connection to ('127.0.0.1', 3020)
------------------------------ Captured log call -------------------------------
INFO     root:ConnectionPool.py:150 Get connection to ('127.0.0.1', 3020)
____________ test_indextest_rebuild_all_tag_indexes_by_multi_input _____________
[gw9] linux -- Python 3.8.10 /usr/bin/python3
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:177: in scenario_wrapper
    _execute_scenario(feature, scenario, request, encoding)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:143: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:113: in _execute_step_function
    return_value = step_func(**kwargs)
tck/conftest.py:243: in wait_job_to_finish
    assert is_finished, f"Fail to finish job {jid}"
E   AssertionError: Fail to finish job 316
E   assert False
----------------------------- Captured stderr call -----------------------------
[2021-09-13 10:17:39,724]:Get connection to ('127.0.0.1', 3020)
------------------------------ Captured log call -------------------------------
INFO     root:ConnectionPool.py:150 Get connection to ('127.0.0.1', 3020)
____________ test_indextest_rebuild_all_edge_indexes_by_empty_input ____________
[gw9] linux -- Python 3.8.10 /usr/bin/python3
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:177: in scenario_wrapper
    _execute_scenario(feature, scenario, request, encoding)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:143: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:113: in _execute_step_function
    return_value = step_func(**kwargs)
tck/conftest.py:243: in wait_job_to_finish
    assert is_finished, f"Fail to finish job {jid}"
E   AssertionError: Fail to finish job 318
E   assert False
----------------------------- Captured stderr call -----------------------------
[2021-09-13 10:18:20,651]:Get connection to ('127.0.0.1', 3020)
------------------------------ Captured log call -------------------------------
INFO     root:ConnectionPool.py:150 Get connection to ('127.0.0.1', 3020)
____________ test_indextest_rebuild_all_edge_indexes_by_multi_input ____________
[gw9] linux -- Python 3.8.10 /usr/bin/python3
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:177: in scenario_wrapper
    _execute_scenario(feature, scenario, request, encoding)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:143: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:113: in _execute_step_function
    return_value = step_func(**kwargs)
tck/conftest.py:243: in wait_job_to_finish
    assert is_finished, f"Fail to finish job {jid}"
E   AssertionError: Fail to finish job 320
E   assert False`

**Comment by bright-starry-sky** [comment]
Some unreasonable test steps have been removed

**Comment by bright-starry-sky** [comment]
`=================================== FAILURES ===================================
__________________ test_lookuptest_no_index_to_use_at_runtime __________________
[gw2] linux -- Python 3.8.10 /usr/bin/python3
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:177: in scenario_wrapper
    _execute_scenario(feature, scenario, request, encoding)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:143: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:113: in _execute_step_function
    return_value = step_func(**kwargs)
tck/conftest.py:427: in execution_should_be_succ
    check_resp(rs, stmt)
common/utils.py:329: in check_resp
    assert resp.is_succeeded(), msg
E   AssertionError: Fail to exec: INSERT VERTEX player(name, age) VALUES hash('Tim'):('Tim', 20);, error: SemanticError: No schema found for `player'
----------------------------- Captured stderr call -----------------------------
[2021-09-13 19:41:04,824]:Get connection to ('127.0.0.1', 8918)
------------------------------ Captured log call -------------------------------
INFO     root:ConnectionPool.py:150 Get connection to ('127.0.0.1', 8918)
________________ test_compare_int_and_float_during_indexscan_1 _________________
[gw0] linux -- Python 3.8.10 /usr/bin/python3
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:177: in scenario_wrapper
    _execute_scenario(feature, scenario, request, encoding)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:143: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:113: in _execute_step_function
    return_value = step_func(**kwargs)
tck/conftest.py:427: in execution_should_be_succ
    check_resp(rs, stmt)
common/utils.py:329: in check_resp
    assert resp.is_succeeded(), msg
E   AssertionError: Fail to exec: INSERT VERTEX weight(WEIGHT) VALUES "Tim Duncan" : (70.5); INSERT VERTEX weight(WEIGHT) VALUES "Tony Parker" : (80.0);, error: SemanticError: No schema found for `weight'
----------------------------- Captured stderr call -----------------------------
[2021-09-13 19:42:04,444]:Get connection to ('127.0.0.1', 8918)
------------------------------ Captured log call -------------------------------
INFO     root:ConnectionPool.py:150 Get connection to ('127.0.0.1', 8918)
=========================== short test summary info ============================
FAILED tck/steps/test_tck.py::test_lookuptest_no_index_to_use_at_runtime - As...
FAILED tck/steps/test_tck.py::test_compare_int_and_float_during_indexscan_1
================== 2 failed, 1068 passed in 831.57s (0:13:51) ==================
/github/home/.local/lib/python3.8/site-packages/pytest_benchmark/logger.py:44: PytestBenchmarkWarning: Benchmarks are automatically disabled because xdist plugin is active.Benchmarks cannot be performed reliably in a parallelized environment.
  warner(PytestBenchmarkWarning(text))
make: *** [Makefile:74: tck] Error 1
Error: Process completed with exit code 2.`

**Comment by bright-starry-sky** [comment]
`[ 92%] Linking CXX executable ../../../bin/bench/toss_bm
[ 93%] Linking CXX executable ../../../bin/test/list_cluster_info_test
[ 93%] Linking CXX executable ../../../bin/test/toss_test
[ 93%] Linking CXX executable ../../../bin/test/delete_edges_test
[ 93%] Linking CXX executable ../../../bin/test/checkpoint_test
Error: Process completed with exit code 137.`

**Comment by bright-starry-sky** [comment]
All `rebuild index job` related test cases tend to be stable. 
I think we can merge this PR first.

**Comment by bright-starry-sky** [comment]
`_______________________ test_lookuptest_functionexprtest _______________________
[gw0] linux -- Python 3.8.10 /usr/bin/python3
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:177: in scenario_wrapper
    _execute_scenario(feature, scenario, request, encoding)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:143: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
/github/home/.local/lib/python3.8/site-packages/pytest_bdd/scenario.py:113: in _execute_step_function
    return_value = step_func(**kwargs)
tck/conftest.py:427: in execution_should_be_succ
    check_resp(rs, stmt)
common/utils.py:329: in check_resp
    assert resp.is_succeeded(), msg
E   AssertionError: Fail to exec: INSERT VERTEX lookup_tag_2(col1, col2, col3, col4) VALUES "220":(true, 100, 100.5, true), "221":(true, 200, 200.5, true), "222":(true, 300, 300.5, true), "223":(true, 400, 400.5, true), "224":(true, 500, 500.5, true), "225":(true, 600, 600.5, true), error: SemanticError: No schema found for `lookup_tag_2'`

**Review by critical27 — APPROVED** [review]

**Review by yixinglu — APPROVED** [review]

**Pull request merged**
