### PR TITLE
Add GitHub actions workflow configuration

### PR DESCRIPTION
**Pull request by yixinglu**
### Reference
- [Workflow syntax for GitHub Actions](https://help.github.com/en/articles/workflow-syntax-for-github-actions)
- [Automating your workflow with GitHub Actions](https://help.github.com/en/categories/automating-your-workflow-with-github-actions)

### CODE REVIEW

**Comment by dutor** [comment]
Jenkins go

**Comment by darionyaphet** [comment]
Please rebase the commits.

**Comment by dutor** [comment]
> Please rebase and compress the commits.

Please note that all commits in a PR will be squashed into one when merged to upstream.

**Comment by darionyaphet** [comment]
> > Please rebase and compress the commits.
> 
> Please note that all commits in a PR will be squashed into one when merged to upstream.

Yep ! But the commit log seems would be retained when merge into master branch ?

**Comment by dutor** [comment]
> > > Please rebase and compress the commits.
> > 
> > 
> > Please note that all commits in a PR will be squashed into one when merged to upstream.
> 
> Yep ! But the commit log seems would be retained when merge into master branch ?

Yes, the commit history will be kept as the verbose message body of the whole commit.

Sure we could make it more concisely while merging.

**Pull request merged**
