### PR TITLE
Implement delete edges

### PR DESCRIPTION
**Pull request by zlcook**
* Delete Edges sentence:
```
DELETE EDGE <edge_type> <vid> -> <vid>[@weight] [, <vid> -> <vid>[@weight] ...]
```

### CODE REVIEW

**Comment by dangleptr** [comment]
Jenkins go

**Comment by zlcook** [comment]
Jenkins go

**Comment by zlcook** [comment]
Jenkins go

**Comment by zlcook** [comment]
> Clean code! Could you explain why we remove the where clause in delete edges?

Just to keep it simple, the `where clause` will be implemented in next PR.

**Comment by bright-starry-sky** [comment]
LGTM . Thanks for taking care of it!

**Comment by dangleptr** [comment]
Jenkins go

**Comment by dangleptr** [comment]
Could you fix the conflicts?  @zlcook

**Comment by zlcook** [comment]
> Could you fix the conflicts? @zlcook 

I will do

**Comment by zlcook** [comment]
Jenkins go

**Pull request merged**
