### PR TITLE
add uuid cache

### PR DESCRIPTION
**Pull request by critical27**
Add uuid cache.

We first check if we cached. If not we need to create one in a CAS operation. If CAS succeeded, we can return the result, if failed, return errorcode.

### CODE REVIEW

**Comment by critical27** [comment]
> Besides uuid cache, for inserting vertex, maybe we could insert UUID directly if the UUID expression used.
> 
> WDYT?

I don't quite get it, for now if we inserting vertex with uuid, need to acquire a uuid at first, if getUUID ok, then it can insert vertex later

**Comment by critical27** [comment]
> Besides uuid cache, for inserting vertex, maybe we could insert UUID directly if the UUID expression used.
> 
> WDYT?

I don't quite get it, if we insert a vertex with uuid, graph need to send two request in sequence, we acquire a uuid at first, if ok, then we can insert vertex.

**Comment by dangleptr** [comment]
> > Besides uuid cache, for inserting vertex, maybe we could insert UUID directly if the UUID expression used.
> > WDYT?
> 
> I don't quite get it, if we insert a vertex with uuid, graph need to send two request in sequence, we acquire a uuid at first, if ok, then we can insert vertex.

Currently,  it is an CAS operation.  Actually, we could insert the uuid directly when inserting vertex.

**Comment by critical27** [comment]
> > > Besides uuid cache, for inserting vertex, maybe we could insert UUID directly if the UUID expression used.
> > > WDYT?
> > 
> > 
> > I don't quite get it, if we insert a vertex with uuid, graph need to send two request in sequence, we acquire a uuid at first, if ok, then we can insert vertex.
> 
> Currently, it is an CAS operation. Actually, we could insert the uuid directly when inserting vertex.

But it seems the leader of uuid and leader of vId maybe not the same one? I think add a field to indicate if its vId is generated by uuid when insert a vertex, WDYT?

**Comment by dangleptr** [comment]
> > > > Besides uuid cache, for inserting vertex, maybe we could insert UUID directly if the UUID expression used.
> > > > WDYT?
> > > 
> > > 
> > > I don't quite get it, if we insert a vertex with uuid, graph need to send two request in sequence, we acquire a uuid at first, if ok, then we can insert vertex.
> > 
> > 
> > Currently, it is an CAS operation. Actually, we could insert the uuid directly when inserting vertex.
> 
> But it seems the leader of uuid and leader of vId maybe not the same one? How about add a field to indicate if vId is generated by uuid when insert a vertex, WDYT?

In InsertVertexExecutor,  if we hit UUID expression,  we could insert the uuid directly.

**Comment by critical27** [comment]
> > > > > Besides uuid cache, for inserting vertex, maybe we could insert UUID directly if the UUID expression used.
> > > > > WDYT?
> > > > 
> > > > 
> > > > I don't quite get it, if we insert a vertex with uuid, graph need to send two request in sequence, we acquire a uuid at first, if ok, then we can insert vertex.
> > > 
> > > 
> > > Currently, it is an CAS operation. Actually, we could insert the uuid directly when inserting vertex.
> > 
> > 
> > But it seems the leader of uuid and leader of vId maybe not the same one? How about add a field to indicate if vId is generated by uuid when insert a vertex, WDYT?
> 
> In InsertVertexExecutor, if we hit UUID expression, we could insert the uuid directly.

Good point, but the cache only works for insert? go, fetch could use it as well.

**Comment by dangleptr** [comment]
Let's close it. UUID will be abandoned in 2.0.

**Pull request closed without merging**
