### PR TITLE
fix IndexScan with label containing parameters

### PR DESCRIPTION
**Pull request by Xscaperrr**
## What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Comment by czpmango** [comment]
Please fix https://github.com/vesoft-inc/nebula/pull/5938/files#r1772790763

**Comment by Xscaperrr** [comment]
> Please fix https://github.com/vesoft-inc/nebula/pull/5938/files#r1772790763

Already fixed it .The corresponding test has been enabled.

**Comment by Xscaperrr** [comment]
@Salieri-004 Please help me with this issue，thanks

**Comment by Salieri-004** [comment]
> @Salieri-004 Please help me with this issue，thanks

Sorry to keep you waiting. LGTM.

**Pull request merged**
