### PR TITLE
split experimental_feature flag

### PR DESCRIPTION
**Pull request by SuperYoko**
## What type of PR is this?
- [ ] bug
- [ ] feature
- [x] enhancement

#### Issue(s) number: 

#4729

#### Description:

experimental flags control toss and data balance at the same time.

## How do you solve it?

add 2 sub flag, current config only allow data balance.

```
# if use experimental features
--enable_experimental_feature=false
# if use toss feature, only work if enable_experimental_feature is true
--enable_toss=false
# if use balance data feature, only work if enable_experimental_feature is true
--enable_data_balance=true
```

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [x] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> add new flag to support only open toss（not suggest）/ data balance feature

### CODE REVIEW

**Comment by panda-sheep** [comment]
Efficient

**Review by wey-gu — APPROVED** [review]
Thanks!

**Comment by wey-gu** [comment]
I created the issue before realizing your pr 🙃.

The issue was aligned with @MuYiYong already.

**Review by pengweisong — APPROVED** [review]
Good job.

**Review by critical27 — APPROVED** [review]

**Comment by jinyingsunny** [comment]
cr了代码，没做验证

**Pull request merged**
