### PR TITLE
Allow users to choose linker like lld to make build faster.

### PR DESCRIPTION
**Pull request by jiayuehua**
#### What type of PR is this?
- [ ] bug
- [* ] feature
- [ ] enhancement

#### What does this PR do?
user can chose linker like lld to make build more faster.

#### Which issue(s)/PR(s) this PR relates to?
none
  
#### Special notes for your reviewer, ex. impact of this fix, etc:
If ci can install lld before build in the future, then can make lld default linker. Now still use bfd as default.

#### Additional context:
none

#### Checklist：
- [* ] Documentation affected （Please add the label if documentation needs to be modified.)
- [ ] Incompatible （If it is incompatible, please describe it and add corresponding label.）
- [ ] Need to cherry-pick （If need to cherry-pick to some branches, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

user in the future need to install lld first to link faster.
#### Release notes：
Please confirm whether to reflect in release notes and how to describe:
>                                                                 `
support lld linker and make build a litter faster

### CODE REVIEW

**Comment by Sophie-Xie** [comment]
[* ] Documentation affected

--> Does this PR affect the document?

**Review by yixinglu — COMMENTED** [review]
I think you shouldn't change the linker config, just by passing the `NEBULA_USE_LINKER ` into cmake in configuring stage.

please see the .github/workflows/pull_request.yml content

**Comment by jiayuehua** [comment]
> I think you shouldn't change the linker config, just by passing the `NEBULA_USE_LINKER ` into cmake in configuring stage.
> 
> please see the .github/workflows/pull_request.yml content
No, the linker config is explicit telling what kind of linker is supported. If set it to CI, Many developer will not notice it, Also Then Can Set NEBULA_USE_LINKER to wrong value like 'notvalidld'. Set it in linkerconfig file developer can now what kind of linker supported.

**Review by yixinglu — APPROVED** [review]

**Comment by yixinglu** [comment]
> > I think you shouldn't change the linker config, just by passing the `NEBULA_USE_LINKER ` into cmake in configuring stage.
> > please see the .github/workflows/pull_request.yml content
> 
> No, the linker config is explicit telling what kind of linker is supported. If set it to CI, Many developer will not notice it, Also Then Can Set NEBULA_USE_LINKER to wrong value like 'notvalidld'. Set it in linkerconfig file developer can know what kind of linker supported.

make sense. And only thing needing to do is just to verify the compiling in multi-platform.

**Review by Aiee — APPROVED** [review]

**Pull request merged**
