### PR TITLE
Fix flex warning about default rule

### PR DESCRIPTION
**Pull request by yixinglu**
#### What type of PR is this?
- [ ] bug
- [ ] feature
- [X] enhancement

#### What does this PR do?

Fixed the warning introduced by #3179 

reference: https://stackoverflow.com/questions/1622493/bison-build-warning-s-option-given-but-default-rule-can-be-matched

### CODE REVIEW

**Comment by jievince** [comment]
> https://github.com/NebulaGraphMatrix/nebula/pull/new/fix-flex-warning

What's it? It jumps to the current page

**Comment by yixinglu** [comment]
> > https://github.com/NebulaGraphMatrix/nebula/pull/new/fix-flex-warning
> 
> What's it? It jumps to the current page

👍 fixed

**Comment by jievince** [comment]
https://github.com/vesoft-inc/nebula/blob/cc9e6bfc0d925573fd4e98b3778191f17dd1f724/src/common/time/parser/datetime_scanner.lex#L60-L64
I don't know why datetime_scanner.lex hasn't added this rule before line 62:
```
[ \t\n\r]                      {}
```
Both scannner.lex and wkt_scanner.lex have it because the last rule `.` couldn't match `\n'.

**Comment by Shylock-Hg** [comment]
> https://github.com/vesoft-inc/nebula/blob/cc9e6bfc0d925573fd4e98b3778191f17dd1f724/src/common/time/parser/datetime_scanner.lex#L60-L64
> 
> 
> I don't know why datetime_scanner.lex hasn't added this rule before line 62:
> ```
> [ \t\n\r]                      {}
> ```
> 
> Both scannner.lex and wkt_scanner.lex have it because the last rule `.` couldn't match `\n'.

This parser can't ignore space directly.

**Comment by jievince** [comment]
> > https://github.com/vesoft-inc/nebula/blob/cc9e6bfc0d925573fd4e98b3778191f17dd1f724/src/common/time/parser/datetime_scanner.lex#L60-L64
> > 
> > I don't know why datetime_scanner.lex hasn't added this rule before line 62:
> > ```
> > [ \t\n\r]                      {}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Both scannner.lex and wkt_scanner.lex have it because the last rule `.` couldn't match `\n'.
> 
> This parser can't ignore space directly.

So change the rule to `[\t\n\r]                      {}` is also ok.

**Comment by yixinglu** [comment]
> > > https://github.com/vesoft-inc/nebula/blob/cc9e6bfc0d925573fd4e98b3778191f17dd1f724/src/common/time/parser/datetime_scanner.lex#L60-L64
> > > 
> > > I don't know why datetime_scanner.lex hasn't added this rule before line 62:
> > > ```
> > > [ \t\n\r]                      {}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Both scannner.lex and wkt_scanner.lex have it because the last rule `.` couldn't match `\n'.
> > 
> > 
> > This parser can't ignore space directly.
> 
> So change the rule to `[\t\n\r] {}` is also ok.

So could i close this PR ?

**Comment by Shylock-Hg** [comment]
> > > > https://github.com/vesoft-inc/nebula/blob/cc9e6bfc0d925573fd4e98b3778191f17dd1f724/src/common/time/parser/datetime_scanner.lex#L60-L64
> > > > 
> > > > I don't know why datetime_scanner.lex hasn't added this rule before line 62:
> > > > ```
> > > > [ \t\n\r]                      {}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Both scannner.lex and wkt_scanner.lex have it because the last rule `.` couldn't match `\n'.
> > > 
> > > 
> > > This parser can't ignore space directly.
> > 
> > 
> > So change the rule to `[\t\n\r] {}` is also ok.
> 
> So could i close this PR ?

Yes, please review this PR #3461

**Comment by Shylock-Hg** [comment]
Replace by #3461

**Pull request closed without merging**
