### PR TITLE
suppress undesired ASAN error

### LINKED ISSUE #3690: ubuntu2004, clang-10 ASAN failed
Almost all ctest with starting thrift server failed.

```
==10683==ERROR: AddressSanitizer: new-delete-type-mismatch on 0x6130000de280 in thread T20:
  object passed to delete has wrong type:
  size of the allocated type:   336 bytes;
  size of the deallocated type: 328 bytes.

...
```

### PR DESCRIPTION
**Pull request by critical27**
#### What type of PR is this?
- [ ] bug
- [ ] feature
- [ ] enhancement

#### What problem(s) does this PR solve?
Issue(s) number: 
#3690

Description:

#### How do you solve it?

Long story. See the #3690 and my post in confluence for details.
  
#### Checklist:
Tests:
- [X] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

#### Release notes:

Please confirm whether to be reflected in release notes and how to describe:
Not related

### CODE REVIEW

**Comment by critical27** [comment]
@Sophie-Xie Maybe this PR doesn't need to cherry pick. Only related to CI

**Comment by SuperYoko** [comment]
> Wouldn't it be better if we kept this error until we found the root cause.

Other issues may be ignored. Maybe we can open an issue to track this.

**Review by SuperYoko — APPROVED** [review]

**Comment by critical27** [comment]
> Wouldn't it be better if we kept this error until we found the root cause.

You could read my post in confluence, almost done there. I will dig more into ASAN if necessary.

**Comment by wenhaocs** [comment]
The PR itself has no problem. But I am concerned about the impact of the bug. One day users find memory leak, will they blame us?

**Review by wenhaocs — DISMISSED** [review]

**Comment by darionyaphet** [comment]
What does `new_delete_type_mismatch` control ?

**Comment by critical27** [comment]
> The PR itself has no problem. But I am concerned about the impact of the bug. One day users find memory leak, will they blame us?

Of course, it is our duty to eliminate memory leak as much as possible. This issue is found when ASAN is turned on, which won't be used in production environment.

**Review by wenhaocs — APPROVED** [review]

**Review by liwenhui-soul — APPROVED** [review]

**Review by cangfengzhs — APPROVED** [review]

**Pull request merged**
