### PR TITLE
add some truncated fixed string case

### PR DESCRIPTION
**Pull request by critical27**
## What type of PR is this?
- [ ] bug
- [ ] feature
- [X] enhancement

#### Description:
We will truncated FIXED_STRING property at the given offset, which make some utf8 character incomplete, for example we will return some strange characters.

Before:
```
CREATE TAG t1(col1 fixed_string(5));
INSERT VERTEX t1(col1) VALUES "2": ("😂😂")
fetch prop on t1 "2" yield t1.col1 as col
+-------+
| col1  |
+-------+
| "😂�" |
+-------+
```

After:
```
fetch prop on t1 "2" yield t1.col1 as col
+------+
| col  |
+------+
| "😂" |
+------+
```

And I have add some test cases that check index has been handle truncated utf8 chracacters correctly.

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Review by cangfengzhs — APPROVED** [review]
LGTM

**Review by SuperYoko — DISMISSED** [review]

**Comment by critical27** [comment]
TCK failed some unexpected cases, will take a look……………… unbelievable

**Comment by critical27** [comment]
Ready now

**Review by yixinglu — DISMISSED** [review]
good job!

**Review by yixinglu — APPROVED** [review]

**Review by cangfengzhs — APPROVED** [review]

**Pull request merged**
