### PR TITLE
improve unreserved keywords feature

### PR DESCRIPTION
**Pull request by steppenwolfyuetong**
As  title.

### CODE REVIEW

**Comment by boshengchen** [comment]
Good, it is reasonable.  The string returned is a label, not a keyword, so lowercase are better.

**Comment by steppenwolfyuetong** [comment]
Rebase and please review, thx.

**Comment by dutor** [comment]
BTW. I love such tiny little improvements like this.
thankyou

**Comment by steppenwolfyuetong** [comment]
Fix confict  and rebase master.
Please review again.

**Comment by dutor** [comment]
Jenkins, please run tests

**Pull request merged**
