### PR TITLE
Fixed dangling pointer in Balancer

### PR DESCRIPTION
**Pull request by dutor**
As title.

### CODE REVIEW

**Comment by dangleptr** [comment]
As original implementation,  after plan_.reset(),  we did call any members in plan_ in onFinished_.  

The program crashed?

**Comment by dutor** [comment]
> As original implementation, after plan_.reset(), we did not access any members in plan_ in onFinished_.
> 
> The program crashed?

After `plan_` got released, `onFinished_` also no longer persists, as well as all data it has captured, `this` in this case. So `running_` cannot be reached any more, even though it's still alive.

**Comment by dangleptr** [comment]
> > As original implementation, after plan_.reset(), we did not access any members in plan_ in onFinished_.
> > The program crashed?
> 
> After `plan_` got released, `onFinished_` also no longer persists, as well as all data it has captured, `this` in this case. So `running_` cannot be reached any more, even though it's still alive.

Fair enough!

**Comment by dutor** [comment]
Thanks to @wadeliuyi for discovering the race condition problem.

**Pull request merged**
