### PR TITLE
Modify the CMakeLists.txt of building jni

### PR DESCRIPTION
**Pull request by laura-ding**

### CODE REVIEW

**Review by dangleptr — CHANGES_REQUESTED** [review]
The orignial purpose for the root CMakeLists.txt under jni is to build jni independently only with its own depencies (glog, stl,  gcc).

**Review by dangleptr — APPROVED** [review]
LGTM.  Thanks for taking care of it.

**Review by bright-starry-sky — APPROVED** [review]

**Comment by bright-starry-sky** [comment]
Please ignore the CI error of snapshot_command_test, I've using #2318 to handle it.

**Review by monadbobo — APPROVED** [review]
LGTM.

**Pull request merged**
