### PR TITLE
To add a web interface to indicate the status of the three daemons

### PR DESCRIPTION
**Pull request by steppenwolfyuetong**
#Issue #237 . To add a web interface to indicate the status of the three daemons

use as follow:

http://127.0.0.1:XXXX/status
http://127.0.0.1:XXXX
When viewing the status of a submodule, use
http://127.0.0.1:XXXX/status/XXXX/XXXX

### CODE REVIEW

**Comment by dutor** [comment]
I noticed that you have some newly added files. Please update the file header according to the presents, with 2018 updated to 2019.

**Comment by steppenwolfyuetong** [comment]
> I noticed that you have some newly added files. Please update the file header according to the presents, with 2018 updated to 2019.

👍👍,  Good catch. I will fix it.

**Comment by steppenwolfyuetong** [comment]
Fix and rebase master, please review again, thx.

**Comment by laura-ding** [comment]
jenkins go

**Comment by laura-ding** [comment]
jenkins go

**Pull request merged**
