### PR TITLE
Condition memory checks on cgroup version.

### PR DESCRIPTION
**Pull request by igrekun**
#### What type of PR is this?
- [ ] bug
- [ ] feature
- [X] enhancement

#### What does this PR do?
Fixes reading memory stats under cgroup v2.

#### Which issue(s)/PR(s) this PR relates to?

https://github.com/vesoft-inc/nebula/issues/3278
  
#### Special notes for your reviewer, ex. impact of this fix, etc:

memory.max return 'max' as string when no --memory flag provided to container on startup.
What should I do about it?

#### Checklist：
- [ ] Documentation affected （Please add the label if documentation needs to be modified.)
- [ ] Incompatible （If it is incompatible, please describe it and add corresponding label.）
- [ ] Need to cherry-pick （If need to cherry-pick to some branches, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

#### Release notes：
Please confirm whether to reflect in release notes and how to describe:
>                                                                 `

### CODE REVIEW

**Review by yixinglu — APPROVED** [review]
LGTM

**Review by jievince — DISMISSED** [review]
Well done! Could you `make clang-format` the code? The lint check has failed.

**Comment by igrekun** [comment]
Sure! Formatted the code.

**Review by yixinglu — APPROVED** [review]

**Review by jievince — APPROVED** [review]

**Review by Aiee — APPROVED** [review]

**Comment by wey-gu** [comment]
@Sophie-Xie please kindly cherry-pick this PR to 2.6.x & 3.x

**Pull request merged**
