### PR TITLE
fixed `show hosts`

### PR DESCRIPTION
**Pull request by caton-hpg**
## What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

#### Issue(s) number: 
https://github.com/vesoft-inc/nebula-ent/issues/1290

## How do you solve it?
Change to default http port for storage now. And fixed later.

```
(root@nebula) [(none)]> show hosts;
+-----------------+------+-----------+----------+--------------+---------------------+------------------------+---------+
| Host            | Port | HTTP port | Status   | Leader count | Leader distribution | Partition distribution | Version |
+-----------------+------+-----------+----------+--------------+---------------------+------------------------+---------+
| "192.168.8.212" | 1779 | 19779     | "ONLINE" | 102          | "nba:100, space3:2" | "nba:100, space3:2"    | ""      |
+-----------------+------+-----------+----------+--------------+---------------------+------------------------+---------+
Got 1 rows (time spent 2637/3544 us)
```

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [x] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [x] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

### CODE REVIEW

**Review by Sophie-Xie — APPROVED** [review]

**Review by Shylock-Hg — CHANGES_REQUESTED** [review]
https://github.com/vesoft-inc/nebula-ent/issues/1290#issuecomment-1258866649

Please check it first.

**Comment by Sophie-Xie** [comment]
> [vesoft-inc/nebula-ent#1290 (comment)](https://github.com/vesoft-inc/nebula-ent/issues/1290#issuecomment-1258866649)
> 
> Please check it first.

Discussed it offline with PD @MuYiYong : This PR doesn't make big changes in v3.3,  just ensure that it is correct when not modifying conf.

**Review by MuYiYong — APPROVED** [review]
OK

**Comment by jinyingsunny** [comment]
> > [vesoft-inc/nebula-ent#1290 (comment)](https://github.com/vesoft-inc/nebula-ent/issues/1290#issuecomment-1258866649)
> > Please check it first.
> 
> Discussed it offline with PD @MuYiYong : This PR doesn't make big changes in v3.3, just ensure that it is correct when not modifying conf.

checked

**Pull request merged**
