### PR TITLE
fix dangling ptr of ActiveHostsMan in ut

### PR DESCRIPTION
**Pull request by critical27**
Fix dangle ptr of kvstore in ProcessorTest.

### CODE REVIEW

**Comment by critical27** [comment]
Jenkins go? why failed

**Comment by critical27** [comment]
Jenkins go!

**Comment by dutor** [comment]
> Jenkins go? why failed

The compiling was aborted due to OOM.

**Comment by whitewum** [comment]
> > Jenkins go? why failed
> 
> The compiling was aborted due to OOM.

is it due to some ut is too large? or bug ? or just the hardware limitation

**Comment by critical27** [comment]
Jenkins go!

**Comment by critical27** [comment]
Jenkins go

**Comment by critical27** [comment]
jenkins go

**Pull request merged**
