### PR TITLE
enhance for 'if not exists'

### PR DESCRIPTION
**Pull request by tong-hao**
### What changes were proposed in this pull request?
Enhance for 'if not exists'.  

### Why are the changes needed?
It can not give a user-friendly  tip when the edge type exists and the user create the same edge type on console.  Detail for #1591

### Does this PR introduce any user-facing change?
Yes.
```
(user@127.0.0.1:3699) [(none)]> create space if not exists test1
The space `test1' existes，nothing changed.
Execution succeeded (Time spent: 41.134/42.466 ms)

(user@127.0.0.1:3699) [test1]> create tag if not exists field()
The tag `field' existes，nothing changed.
Execution succeeded (Time spent: 28.77/29.787 ms)

(user@127.0.0.1:3699) [test1]> create tag index if not exists idx1 on field(src_pri_value);
The tag index `idx1' existes，nothing changed.
Execution succeeded (Time spent: 1.68/2.95 ms)

(user@127.0.0.1:3699) [(none)]> create edge if not exists choose();
The edge `choose' existes，nothing changed.
Execution succeeded (Time spent: 19.458/21.182 ms)

(user@127.0.0.1:3699) [test1]> create edge index if not exists idx2 on choose(grade);
The edge index `idx2' existes，nothing changed.
Execution succeeded (Time spent: 1.074/2.121 ms)
```

### How was this patch tested?
Manual testing

### CODE REVIEW

**Comment by Shylock-Hg** [comment]
The issue #1591 say we need alert user if create a exist schema which contains the same name schema but not expected by user.

**Comment by tong-hao** [comment]
> The issue #1591 say we need alert user if create a exist schema which contains the same name schema but not expected by user.

Something wrong?
First time, It cannot show the message.
```
(user@127.0.0.1:3699) [(none)]> create edge if not exists choose2()

Execution succeeded (Time spent: 3.199/4.38 ms)

Thu Jan 16 20:24:26 2020

(user@127.0.0.1:3699) [test1]> create edge if not exists choose2()
The edge `choose2' has already created.
Execution succeeded (Time spent: 1.316/2.474 ms)

Thu Jan 16 20:24:29 2020


```

**Comment by tong-hao** [comment]
> If I understood right, all you want is to show a message indicating that the entry already exists.
> 
> But I dont think this is the right way to do so. It's better to do it on the meta side, so that we dont need to change `Status`, to add another callback or to add an extra RPC(which is not atomical).
> 
> All we need is to check the existence(with the creation interface itself) and set a proper message if necessary.

@dutor  The message of meta side cannnot spread to graphd side. There are just code. Maybe I need to change thrift rpc file.

**Comment by Shylock-Hg** [comment]
> > The issue #1591 say we need alert user if create a exist schema which contains the same name schema but not expected by user.
> 
> Something wrong?
> First time, It cannot show the message.
> 
> ```
> (user@127.0.0.1:3699) [(none)]> create edge if not exists choose2()
> 
> Execution succeeded (Time spent: 3.199/4.38 ms)
> 
> Thu Jan 16 20:24:26 2020
> 
> (user@127.0.0.1:3699) [test1]> create edge if not exists choose2()
> The edge `choose2' has already created.
> Execution succeeded (Time spent: 1.316/2.474 ms)
> 
> Thu Jan 16 20:24:29 2020
> ```

Yes, we may not alert if the exist schema is what user expect(same with user want to create).

**Comment by tong-hao** [comment]
> > > The issue #1591 say we need alert user if create a exist schema which contains the same name schema but not expected by user.
> > 
> > 
> > Something wrong?
> > First time, It cannot show the message.
> > ```
> > (user@127.0.0.1:3699) [(none)]> create edge if not exists choose2()
> > 
> > Execution succeeded (Time spent: 3.199/4.38 ms)
> > 
> > Thu Jan 16 20:24:26 2020
> > 
> > (user@127.0.0.1:3699) [test1]> create edge if not exists choose2()
> > The edge `choose2' has already created.
> > Execution succeeded (Time spent: 1.316/2.474 ms)
> > 
> > Thu Jan 16 20:24:29 2020
> > ```
> 
> Yes, we may not alert if the exist schema is what user expect(same with user want to create).In the other side, we want to alert only when the exist schema is different with the user want.


Thank you for you patient reply. I think I understand it now. I ignored  the props before.
If the name exists  and  the schema of edge  is different, we should alert. 
```
(user@127.0.0.1:3699) [test1]> create edge if not exists choose2()
The edge `choose2' has already created.
Execution succeeded (Time spent: 1.316/2.474 ms)
```
If the name exists and the schema of edge is same, just show 'Execution succeeded'.
```
(user@127.0.0.1:3699) [(none)]> create edge if not exists choose2()

Execution succeeded (Time spent: 3.199/4.38 ms)
```

I will check the schema and name  on the side of graph. What do you think?

**Comment by Shylock-Hg** [comment]
> > > > The issue #1591 say we need alert user if create a exist schema which contains the same name schema but not expected by user.
> > > 
> > > 
> > > Something wrong?
> > > First time, It cannot show the message.
> > > ```
> > > (user@127.0.0.1:3699) [(none)]> create edge if not exists choose2()
> > > 
> > > Execution succeeded (Time spent: 3.199/4.38 ms)
> > > 
> > > Thu Jan 16 20:24:26 2020
> > > 
> > > (user@127.0.0.1:3699) [test1]> create edge if not exists choose2()
> > > The edge `choose2' has already created.
> > > Execution succeeded (Time spent: 1.316/2.474 ms)
> > > 
> > > Thu Jan 16 20:24:29 2020
> > > ```
> > 
> > 
> > Yes, we may not alert if the exist schema is what user expect(same with user want to create).In the other side, we want to alert only when the exist schema is different with the user want.
> 
> Thank you for you patient reply. I think I understand it now. I ignored the props before.
> If the name exists and the schema of edge is different, we should alert.
> 
> ```
> (user@127.0.0.1:3699) [test1]> create edge if not exists choose2()
> The edge `choose2' has already created.
> Execution succeeded (Time spent: 1.316/2.474 ms)
> ```
> 
> If the name exists and the schema of edge is same, just show 'Execution succeeded'.
> 
> ```
> (user@127.0.0.1:3699) [(none)]> create edge if not exists choose2()
> 
> Execution succeeded (Time spent: 3.199/4.38 ms)
> ```
> 
> I will check the schema and name on the side of graph. What do you think?

Ok. Gook luck.

**Comment by dangleptr** [comment]
It change the behavior of some commands.  Maybe we could address it in 2.0.   Close it now. Thx.

**Pull request closed without merging**
