### PR TITLE
show hosts in order.

### PR DESCRIPTION
**Pull request by xuguruogu**
As show hosts col(Leader distribution) not shown in order, the different row may have the different orders. It is human-readable to make it display in order.

### CODE REVIEW

**Comment by dutor** [comment]
Close for CLA testing

**Comment by dutor** [comment]
Close for CLA testing

**Comment by dangleptr** [comment]
Good one.  Could you show me what's the display looks like in console now?

**Comment by xuguruogu** [comment]
image

**Review by critical27 — APPROVED** [review]
Good job!

**Review by dangleptr — APPROVED** [review]
Well done. Thanks for your contribution.

**Pull request merged**
