### PR TITLE
Pragma2ifndef

### PR DESCRIPTION
**Pull request by jiayuehua**
#### What type of PR is this?
- [ ] bug
- [ ] feature
- [x] enhancement

#### What problem(s) does this PR solve?
Issue(s) number: 
https://github.com/vesoft-inc/nebula/issues/3676
Description:

#### How do you solve it?
replace all pragma once with ifndef...

  
#### Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

#### Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Comment by jievince** [comment]
What's bug of `#program once`?

**Comment by jiayuehua** [comment]
> What's bug of `#pragma once`?

pragma once is not standard c++. Also Its a change that sherman suggested.

**Review by czpmango — APPROVED** [review]

**Review by CPWstatic — DISMISSED** [review]

**Comment by critical27** [comment]
Don't merge please, if you want to forbid `pragma once`, maybe add it in python-lint

**Comment by jiayuehua** [comment]
> Don't merge please, if you want to forbid `pragma once`, maybe add it in python-lint

what's the reason? add to python-lint will make the pull_request/lint check fail.

**Comment by critical27** [comment]
> > Don't merge please, if you want to forbid `pragma once`, maybe add it in python-lint
> 
> what's the reason? add to python-lint will make the pull_request/lint check fail.

I mean you could add it to python-lint to prevent usage in future

**Review by czpmango — APPROVED** [review]

**Review by critical27 — APPROVED** [review]

**Comment by critical27** [comment]
Good job~

**Review by critical27 — APPROVED** [review]

**Pull request merged**
