### PR TITLE
enhance var: single element var can be used as primary expression. support global var stored in session.

### PR DESCRIPTION
**Pull request by xuguruogu**
https://discuss.nebula-graph.com.cn/t/topic/1134

```
$var = yield 1;
go ... where edge.prop == hash($var);
```

```
global $var = yield 1;

// the whole session can access it by:
yield $var;
```

### CODE REVIEW

**Comment by xuguruogu** [comment]
It seems depends on #2228

**Comment by Amber1990Zhang** [comment]
guess doc is needed if merged. I'll take care this.

**Comment by dangleptr** [comment]
Currently session implementation is not good enough.  After FO,  the session informaiton will be lost.  
So store the variable together with session is eally satisfed your requirements?

**Comment by xuguruogu** [comment]
> Currently session implementation is not good enough. After FO, the session informaiton will be lost.
> So store the variable together with session is eally satisfed your requirements?

As multi spaces may created in same cluster. Session wise global variable is enough.

**Comment by CPWstatic** [comment]
This will be considered in a later v2.0.

**Pull request closed without merging**
