### PR TITLE
fix folly::stringPrintf when ref empty str

### PR DESCRIPTION
**Pull request by pengweisong**
## What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

#### Issue(s) number: 
https://github.com/vesoft-inc/nebula/issues/4926
#### Description:
when the sym_ in PropertyExpression is empty, return reference of string and pass it to folly::stringFormat will crash.

```
(gdb) bt
#0  0x00007f26e967f079 in vfprintf () from /lib64/libc.so.6
#1  0x00007f26e96aa179 in vsnprintf () from /lib64/libc.so.6
#2  0x0000000002c2a2b3 in ?? ()
#3  0x0000000002c2b737 in folly::stringVPrintf[abi:cxx11](char const*, __va_list_tag*) ()
#4  0x0000000002c2b8df in folly::stringPrintf[abi:cxx11](char const*, ...) ()
#5  0x00000000014ce1ca in nebula::storage::UpdateResNode<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::doExecute(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#6  0x00000000014bd030 in nebula::storage::RelNode<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::execute(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#7  0x00000000014bcd86 in nebula::storage::RelNode<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::doExecute(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#8  0x00000000014bd030 in nebula::storage::RelNode<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::execute(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#9  0x00000000014bbfb0 in nebula::storage::UpdateVertexProcessor::doProcess(nebula::storage::cpp2::UpdateVertexRequest const&) ()
#10 0x00000000028b3a27 in virtual thunk to apache::thrift::concurrency::FunctionRunner::run() ()
#11 0x0000000002a0ea38 in apache::thrift::concurrency::ThreadManager::Impl::Worker::run() ()
#12 0x0000000002a10b3e in apache::thrift::concurrency::PthreadThread::threadMain(void*) ()
#13 0x00007f26e9a07ea5 in start_thread () from /lib64/libpthread.so.0
#14 0x00007f26e9730b0d in clone () from /lib64/libc.so.6
```

## How do you solve it?

just use `exp->toString()`, in which will test empty, and then copy.

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Review by jievince — DISMISSED** [review]

**Comment by critical27** [comment]
@jievince, does graphd add something like constant folding?

```
UPDATE  VERTEX ON `aa` 'a:1005' SET `name` = 'test' YIELD 'a:1005' AS `aId`, `name`;
```
The root cause is that in `YIELD 'a:1005' AS aId`, previously it is a PropertyExpression or at least storaged assume it is. But it is a now a `ConstantExpression`, see the debug info below
image

**Comment by jievince** [comment]
'a:1005' is a `ConstantExpression` generated by the parser.
The graph validator doesn't check the non-property related expr in the yield clause of update statement. 
Do we allow such usage?

**Comment by critical27** [comment]
Ok, I see. You could just remove the `static_cast`, and use `exp->toString` here. That could solve it. @pengweisong

**Comment by pengweisong** [comment]
> Ok, I see. You could just remove the `static_cast`, and use `exp->toString` here. That could solve it. @pengweisong

OK, fixed, and takes some time to compile and verify the sentences in the issue.

**Comment by HarrisChu** [comment]
could we add some tck cases?

**Comment by pengweisong** [comment]
> could we add some tck cases?
OK, I'll try.

**Review by critical27 — APPROVED** [review]

**Review by jievince — APPROVED** [review]

**Pull request merged**
