### PR TITLE
[doc] remove doc

### PR DESCRIPTION
**Pull request by Amber1990Zhang**
I removed doc in this repo.
New doc repo: https://github.com/vesoft-inc/nebula-docs
Doc site:https://docs.nebula-graph.io/

### CODE REVIEW

**Comment by Amber1990Zhang** [comment]
> I'm OK
> Let's submit a new pr to improve ToC & reference
> Let's ignore the change to getstarted.md

Do we need a doc TOC here? I think we just update the link

**Comment by whitewum** [comment]
At least one link to the new repo

**Comment by Amber1990Zhang** [comment]
> At least one link to the new repo

of course. Once the refactor is done

**Comment by Amber1990Zhang** [comment]
> At least one link to the new repo

All links fixed in https://github.com/vesoft-inc/nebula/pull/2107

**Pull request merged**
