### PR TITLE
Lookup subgraph format yield

### PR DESCRIPTION
**Pull request by nevermore3**
1、 Must add YIELD clause in the lookup vertex、lookup edge & subgraph sentence
2、Remove the default output columns 【SrcVid, DstVid, Ranking】in lookup edge
3、Remove the default output column 【VertexID】in lookup vertex

### CODE REVIEW

**Comment by nevermore3** [comment]
subjob of https://github.com/vesoft-inc/nebula/issues/3135

**Review by CPWstatic — DISMISSED** [review]
LGTM. Please fix the coflict.

**Review by yixinglu — COMMENTED** [review]
Why delete some tests?

**Comment by nevermore3** [comment]
> Why delete some tests?

Those deleted test cases are duplicate

**Review by yixinglu — APPROVED** [review]
LGTM

**Review by CPWstatic — APPROVED** [review]

**Comment by cooper-lzy** [comment]
https://github.com/vesoft-inc/nebula-docs-cn/pull/1359

**Pull request merged**
