### PR TITLE
set rocksdb_disable_wal to false by default

### PR DESCRIPTION
**Pull request by critical27**
As title.

### CODE REVIEW

**Comment by darionyaphet** [comment]
Keeping both the RocksDB and the Raft's WAL

**Comment by whitewum** [comment]
Does this flag make write much more slower? 
Do you have or need any test?

**Comment by dangleptr** [comment]
> Does this flag make write much more slower?
> Do you have or need any test?

Yes, of course, we need to test it.  According to my experience,  it has just about 10~20% improvement for high load write test.  For stable,  we close it for temporarily by default. 

Thanks.

**Comment by xuguruogu** [comment]
> > Does this flag make write much more slower?
> > Do you have or need any test?
> 
> Yes, of course, we need to test it. According to my experience, it has just about 10~20% improvement for high load write test. For stable, we close it for temporarily by default.
> 
> Thanks.

I also meet so much unstable issues. Hope this can help me.

**Comment by dangleptr** [comment]
> > > Does this flag make write much more slower?
> > > Do you have or need any test?
> > 
> > 
> > Yes, of course, we need to test it. According to my experience, it has just about 10~20% improvement for high load write test. For stable, we close it for temporarily by default.
> > Thanks.
> 
> I also meet so much unstable issues. Hope this can help me.

Yes, you could try it.  In some cases,  we found the memory data lost will cause snapshot  pulling when restart the cluster. 
It will cause lots of unstable problems.

**Pull request merged**
