### PR TITLE
Added support to disable -Werror

### PR DESCRIPTION
**Pull request by dutor**
This is for end users those who want to build from source, allowing them to disable `-Werror` without tweaking the code.

### CODE REVIEW

**Comment by dutor** [comment]
> Em... Do you want to be compatible for different gcc versions?

What do you mean by _compatible_? I can't see there is anything about compiler itself.

**Comment by dangleptr** [comment]
> > Em... Do you want to be compatible for different gcc versions?
> 
> What do you mean by _compatible_? I can't see there is anything about compiler itself.

Is there any warnings now?  Only for some different compilers,  some warnings maybe dumped.

**Comment by dutor** [comment]
> Em... Do you want to be compatible for different gcc versions?

I think I got you now.

There are chances that we cannot cover all situations for environments of users. For example, users may use the latest compiler which can trigger more warnings, and we might not catch up immediately.

**Comment by dangleptr** [comment]
> > Em... Do you want to be compatible for different gcc versions?
> 
> I think I got you now.
> 
> There are chances that we cannot cover all situations for environments of users. For example, users may use the latest compiler which can trigger more warnings, and we might not catch up immediately.

Nice.

**Pull request merged**
