### PR TITLE
Optimize/contains push down in lookup

### PR DESCRIPTION
**Pull request by MMyheart**

### CODE REVIEW

**Review by critical27 — APPROVED** [review]
LGTM, good job

**Comment by bright-starry-sky** [comment]
Good job. LGTM. Please resolve the conflicts.

**Comment by yixinglu** [comment]
There are so many conflicts in this PR, could you try to solve it recently？

**Comment by xtcyclist** [comment]
This PR has made significant changes. And, it has been idle for too long. It seems to be a good PR, but there is no context provided. Since a long time has passed, we are probably not able to merge such a large PR. We shall probabaly close it for now.

**Pull request closed without merging**
