### PR TITLE
LABEL in could be any string

### PR DESCRIPTION
**Pull request by liwenhui-soul**
normally, string like "zone127.0.0.1_111" is illegal for name_label, this pr is to make these illegal strings in `` could be legal for name_label.

### CODE REVIEW

**Comment by czpmango** [comment]
Please add some test cases.

**Comment by darionyaphet** [comment]
SO, this PR can replace string with name label?

**Comment by liwenhui-soul** [comment]
> SO, this PR can replace `name_label` with `STRING`?

yes

**Comment by liwenhui-soul** [comment]
> Please add some test cases.

done

**Review by czpmango — APPROVED** [review]

**Review by critical27 — APPROVED** [review]
Well done

**Pull request merged**
