### PR TITLE
Fix the issue that the query results will still contain the expired e…

### PR DESCRIPTION
**Pull request by luyade**
…dges if we use go reversely

#### What type of PR is this?
- [ ] bug

#### What does this PR do?
Fix an issue that the query results still contain the expired edges when use go reversely

#### Checklist:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the corresponding label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

#### Release notes:

Please confirm whether to be reflected in release notes and how to describe:
>                                                                 `

### CODE REVIEW

**Comment by luyade** [comment]
@Sophie-Xie any comment? does it look OK?

**Comment by Sophie-Xie** [comment]
> @Sophie-Xie any comment? does it look OK?

Thanks. I assign it to others, pls wait for their review.

**Review by Nivras — APPROVED** [review]
LGTM, thanks

**Review by critical27 — APPROVED** [review]
Gooood job~ thx~

**Pull request merged**
