### PR TITLE
fix drop host from a zone

### PR DESCRIPTION
**Pull request by darionyaphet**

### CODE REVIEW

**Comment by darionyaphet** [comment]
please wait for a minute ...

**Review by critical27 — COMMENTED** [review]
Ready? Generally LGTM, add some test if possible

**Review by critical27 — APPROVED** [review]
Good job

**Comment by critical27** [comment]
Close #2846

**Review by bright-starry-sky — APPROVED** [review]
Good job. LGTM.

**Comment by HarrisChu** [comment]
how about a zone with only one host, could it be dropped?

**Comment by darionyaphet** [comment]
> how about a zone with only one host (no parts), could it be dropped?

In my opinion, it's OK

**Comment by HarrisChu** [comment]
> > how about a zone with only one host (no parts), could it be dropped?
> 
> In my opinion, it's OK

it's ok for me too, just confirmation.
if it's ok, I will add more cases, e.g. add group via a zone without any hosts.

**Comment by yixinglu** [comment]
@darionyaphet please fix the format of this PR. you can use following commands to do that:

```shell
$ cd /path/to/build/directory
$ make clang-format
```

**Comment by darionyaphet** [comment]
> @darionyaphet please fix the format of this PR. you can use following commands to do that:
> 
> ```shell
> $ cd /path/to/build/directory
> $ make clang-format
> ```

thanks but it looks like there's no such command?

```
-- Build files have been written to: /data/darion/work/nebula/build
xargs: clang-format: No such file or directory
make[3]: *** [CMakeFiles/clang-format.dir/build.make:70: CMakeFiles/clang-format] Error 127
make[2]: *** [CMakeFiles/Makefile2:2295: CMakeFiles/clang-format.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2302: CMakeFiles/clang-format.dir/rule] Error 2
make: *** [Makefile:264: clang-format] Error 2
```

**Review by yixinglu — APPROVED** [review]

**Review by critical27 — APPROVED** [review]

**Comment by yixinglu** [comment]
> > @darionyaphet please fix the format of this PR. you can use following commands to do that:
> > ```shell
> > $ cd /path/to/build/directory
> > $ make clang-format
> > ```
> 
> thanks @yixinglu but it looks like there's no such command?
> 
> ```
> -- Build files have been written to: /data/darion/work/nebula/build
> xargs: clang-format: No such file or directory
> make[3]: *** [CMakeFiles/clang-format.dir/build.make:70: CMakeFiles/clang-format] Error 127
> make[2]: *** [CMakeFiles/Makefile2:2295: CMakeFiles/clang-format.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:2302: CMakeFiles/clang-format.dir/rule] Error 2
> make: *** [Makefile:264: clang-format] Error 2
> ```
> 
> By the way, only update branch will cause the format check failed?

Append the path `/opt/vesoft/toolset/clang/10.0.0/bin` to the `PATH` environment variable.

**Pull request merged**
