### PR TITLE
doc: Community in Badges

### PR DESCRIPTION
**Pull request by wey-gu**
## What type of PR is this?
- [ ] bug
- [ ] feature
- [ ] enhancement

#### Description:

- rebranding name of Nebula Graph as NebulaGraph
- fixed arch image for CN readme
- Added Badges for exposing community meetings, discussions, etc.

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [x] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Comment by Sophie-Xie** [comment]
Good job!

Do you need to add Chinese forums and Tencent conferences to English md?
image

**Comment by wey-gu** [comment]
> Good job!
> 
> Do you need to add Chinese forums and Tencent conferences to English md? image

Yes, that's done on purpose for the reason:
1. most of the fresh visitors won't notice the CN readme, thus seeing it here with Chinese char could have a better chance navigate them there :)
2. it will be ignored for global visitors as they are Chinese chars

**Comment by wey-gu** [comment]
> Good job!
> 
> Do you need to add Chinese forums and Tencent conferences to English md? image

Yes, that's done on purpose for the reason:
1. most of the fresh visitors won't notice the CN readme, thus seeing it here with Chinese char could have a better chance navigate them there :)
2. it will be ignored for global visitors as they are Chinese chars

**Review by Sophie-Xie — APPROVED** [review]

**Comment by whitewum** [comment]
> ## What type of PR is this?
> * [ ]  bug
> * [ ]  feature
> * [x]  enhancement
> 
> ## What problem(s) does this PR solve?
> #### Issue(s) number:
> #### Description:
> * fixed naming of Nebula Graph as NebulaGraph
> * fixed arch image for CN readme
> * Added Badges for exposing community meetings, discussions, etc.
> 
> ## How do you solve it?
> ## Special notes for your reviewer, ex. impact of this fix, design document, etc:
> ## Checklist:
> Tests:
> 
> * [ ]  Unit test(positive and negative cases)
> * [ ]  Function test
> * [ ]  Performance test
> * [x ] N/A
> 
> Affects:
> 
> * [ ]  Documentation affected (Please add the label if documentation needs to be modified.)
> * [ ]  Incompatibility (If it breaks the compatibility, please describe it and add the label.）
> * [ ]  If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
> * [ ]  Performance impacted: Consumes more CPU/Memory
> 
> ## Release notes:
> Please confirm whether to be reflected in release notes and how to describe:
> 
> > ex. Fixed the bug .....

 A space between Nebula and Graph heavily changes the VI.
This had been a meeting of discussionion and was determined in 2019 as **Nebula Graph**.

**Comment by wey-gu** [comment]
@Sophie-Xie @whitewum Sorry I thought that was a new thing to do rebrand :-P, reverted those changes now.

**Review by randomJoe211 — APPROVED** [review]

**Review by Sophie-Xie — DISMISSED** [review]

**Review by whitewum — APPROVED** [review]

**Review by Sophie-Xie — DISMISSED** [review]

**Review by Sophie-Xie — APPROVED** [review]
Good job!

**Review by randomJoe211 — APPROVED** [review]

**Pull request merged**
