### PR TITLE
rename max_parts_num and set the default value of max_parts_num to 16…

### PR DESCRIPTION
**Pull request by knightXun**
I rename default_max_parts_num to max_parts_num, and set this default value big enough

### CODE REVIEW

**Comment by Shylock-Hg** [comment]
The name in cloud branch should keep same too.

**Comment by knightXun** [comment]
> The name in cloud branch should keep same too.

this is to cloud branch

**Comment by laura-ding** [comment]
@knightXun you need to add `--max_parts_num=100` when starting the nebula servers.

**Comment by Shylock-Hg** [comment]
I think you could submit the feature to master.

**Pull request merged**
