### PR TITLE
Support TTL cache inside ConcurrentLRUCache

### PR DESCRIPTION
**Pull request by dangleptr**
In many cases,  users could load all vertices.  
LRU is not suitable,  so we support Map cache for all data with TTL feature. 
The performance has been improved by 2.7x compare to LRU cache.

### CODE REVIEW

**Comment by dangleptr** [comment]
@xuguruogu Do you want to try it.

**Comment by xuguruogu** [comment]
what if some keys never access, how to evict them

**Comment by dangleptr** [comment]
> what if some keys never access, how to evict them

Em... The cache is used for situation all the vertices could be hold in cache. So is it really a problem?

**Comment by xuguruogu** [comment]
> > what if some keys never access, how to evict them
> 
> Em... The cache is used for situation all the vertices could be hold in cache. So is it really a problem?

Does every space share the same cache?

**Comment by dangleptr** [comment]
> > > what if some keys never access, how to evict them
> > 
> > 
> > Em... The cache is used for situation all the vertices could be hold in cache. So is it really a problem?
> Does every space share the same cache?

That's a good question. Currently, all spaces share the same vertexCache.  Maybe "one space one cache"  is  a better choice.  wdyt?

**Comment by xuguruogu** [comment]
> > > > what if some keys never access, how to evict them
> > > 
> > > 
> > > Em... The cache is used for situation all the vertices could be hold in cache. So is it really a problem?
> > > Does every space share the same cache?
> 
> That's a good question. Currently, all spaces share the same vertexCache. Maybe "one space one cache" is a better choice. wdyt?

I prefer to share the cache for all spaces. Otherwise, it will have trouble with memory control.

**Comment by dangleptr** [comment]
> > > > > what if some keys never access, how to evict them
> > > > 
> > > > 
> > > > Em... The cache is used for situation all the vertices could be hold in cache. So is it really a problem?
> > > > Does every space share the same cache?
> > 
> > 
> > That's a good question. Currently, all spaces share the same vertexCache. Maybe "one space one cache" is a better choice. wdyt?
> 
> I prefer to share the cache for all spaces. Otherwise, it will have trouble with memory control.

OK.  Could you try it in your env?  F14Map is also an  implementation of cuckoo Hash with vector instructions used to accelerate the scan inside one bucket.  I think the performance should be same with yours in #2264

**Comment by xuguruogu** [comment]
> > > > > > what if some keys never access, how to evict them
> > > > > 
> > > > > 
> > > > > Em... The cache is used for situation all the vertices could be hold in cache. So is it really a problem?
> > > > > Does every space share the same cache?
> > > 
> > > 
> > > That's a good question. Currently, all spaces share the same vertexCache. Maybe "one space one cache" is a better choice. wdyt?
> > 
> > 
> > I prefer to share the cache for all spaces. Otherwise, it will have trouble with memory control.
> 
> OK. Could you try it in your env? F14Map is also an implementation of cuckoo Hash with vector instructions used to accelerate the scan inside one bucket. I think the performance should be same with yours in #2264

As we may change the space for test frequently. It seems the cache may has no effect if space changed.

**Comment by dangleptr** [comment]
> > > > > > > what if some keys never access, how to evict them
> > > > > > 
> > > > > > 
> > > > > > Em... The cache is used for situation all the vertices could be hold in cache. So is it really a problem?
> > > > > > Does every space share the same cache?
> > > > 
> > > > 
> > > > That's a good question. Currently, all spaces share the same vertexCache. Maybe "one space one cache" is a better choice. wdyt?
> > > 
> > > 
> > > I prefer to share the cache for all spaces. Otherwise, it will have trouble with memory control.
> > 
> > 
> > OK. Could you try it in your env? F14Map is also an implementation of cuckoo Hash with vector instructions used to accelerate the scan inside one bucket. I think the performance should be same with yours in #2264
> 
> As we may change the space for test frequently. It seems the cache may has no effect if space changed.

Em... If so, how do you test #2264

**Comment by xuguruogu** [comment]
> > > > > > > > what if some keys never access, how to evict them
> > > > > > > 
> > > > > > > 
> > > > > > > Em... The cache is used for situation all the vertices could be hold in cache. So is it really a problem?
> > > > > > > Does every space share the same cache?
> > > > > 
> > > > > 
> > > > > That's a good question. Currently, all spaces share the same vertexCache. Maybe "one space one cache" is a better choice. wdyt?
> > > > 
> > > > 
> > > > I prefer to share the cache for all spaces. Otherwise, it will have trouble with memory control.
> > > 
> > > 
> > > OK. Could you try it in your env? F14Map is also an implementation of cuckoo Hash with vector instructions used to accelerate the scan inside one bucket. I think the performance should be same with yours in #2264
> > 
> > 
> > As we may change the space for test frequently. It seems the cache may has no effect if space changed.
> 
> Em... If so, how do you test #2264

The cache in #2264 will try to reclaim the slots that contain expired data. If space changed, new data will replace the data never access.

**Comment by dangleptr** [comment]
> > > > > > > > > what if some keys never access, how to evict them
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Em... The cache is used for situation all the vertices could be hold in cache. So is it really a problem?
> > > > > > > > Does every space share the same cache?
> > > > > > 
> > > > > > 
> > > > > > That's a good question. Currently, all spaces share the same vertexCache. Maybe "one space one cache" is a better choice. wdyt?
> > > > > 
> > > > > 
> > > > > I prefer to share the cache for all spaces. Otherwise, it will have trouble with memory control.
> > > > 
> > > > 
> > > > OK. Could you try it in your env? F14Map is also an implementation of cuckoo Hash with vector instructions used to accelerate the scan inside one bucket. I think the performance should be same with yours in #2264
> > > 
> > > 
> > > As we may change the space for test frequently. It seems the cache may has no effect if space changed.
> > 
> > 
> > Em... If so, how do you test #2264
> 
> The cache in #2264 will try to reclaim the slots that contain expired data. If space changed, new data will replace the data never access.

Em..... I see.

**Comment by dangleptr** [comment]
Close it.  #2264  is a better choice with TTL feature. Let's go back there.

**Pull request closed without merging**
