### PR TITLE
change time point calculate in ttl

### PR DESCRIPTION
**Pull request by pengweisong**
## What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

#### Description:

When insert ttl field with now() which is calculated by time(NULL). When check if the ttl field valid, we use time::WallClock before, which will drift from time(NULL) with time going.

## How do you solve it?

both use time(NULL)

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Review by critical27 — APPROVED** [review]

**Review by panda-sheep — DISMISSED** [review]
Good，thx

**Review by critical27 — APPROVED** [review]

**Comment by critical27** [comment]
@shanlai Tell me if you have verified it~

**Review by critical27 — DISMISSED** [review]

**Review by panda-sheep — APPROVED** [review]
Good job

**Review by panda-sheep — APPROVED** [review]

**Review by critical27 — APPROVED** [review]

**Comment by shanlai** [comment]
@critical27 Verification passed

**Pull request merged**
