### PR TITLE
Reduced queueing latency

### PR DESCRIPTION
**Pull request by dutor**
`IOThreadPoolExecutor` and `CPUThreadPoolExecutor` differ in that, threads in the latter share a single task queue, while there is one queue for each thread in the former. Given that, in the query bound(aka. GetNeighbors) scenario,  there are chances that light tasks are queued after some heavy ones. This will increase the overall latency, even worse if we split the light tasks in order to execute them concurrently. 

By using `CPUThreadPoolExecutor`, we could minimize the queueing latency. At the meantime, the concurrent execution can be fully utilized.

As a result, latency can be reduced by more than a half in the LDBC workload.

### CODE REVIEW

**Comment by dangleptr** [comment]
> FYI. Latency can be reduced by more than a half in the LDBC workload.

What's the concurrency setting (max_handlers_per_req) in your load test.

**Comment by dutor** [comment]
> > FYI. Latency can be reduced by more than a half in the LDBC workload.
> 
> What's the concurrency setting (max_handlers_per_req) in your load test.

256

**Comment by dangleptr** [comment]
Em...  Typically,  we use max_handlers_per_req = 1 in load test.  That's because the larger concurrency setting will hurt the throughput in high load mode.  
What's your max throughput with 256?

**Comment by whitewum** [comment]
#1631

**Comment by dutor** [comment]
> Em... Typically, we use max_handlers_per_req = 1 in load test. That's because the larger concurrency setting will hurt the throughput in high load mode.
With that setting, and `GO 3 STEPS...`, there is always one thread saturated, which leads to latency burst up.

> What's your max throughput with 256?
With the same client concurrency(28 conn), this PR boosts the QPS from 400 to 800, P99 400ms to 200ms.

**Comment by dangleptr** [comment]
> With that setting, and GO 3 STEPS..., there is always one thread saturated while the others are nearly idle, which leads to latency burst up.

Indeed,  with 1 max_handlers_per_req setting,  the large request will block all requests in that thread.  What's the vertices requested at most in your situation.

**Comment by dutor** [comment]
> Indeed, with 1 max_handlers_per_req setting, the large request will block all requests in that thread. What's the vertices requested at most in your situation.

Upto hundreds of thousands.

**Comment by dangleptr** [comment]
> With the same client concurrency(28 conn), this PR boosts the QPS from 400 to 800, P99 400ms to 200ms.

I suggest we'd better test the 1-step request with 1 max_handlers_per_req setting again.  
Because cpuThreadPool has high contention than ioThreadPool for normal requests.

**Comment by dutor** [comment]
> > With the same client concurrency(28 conn), this PR boosts the QPS from 400 to 800, P99 400ms to 200ms.
> 
> I suggest we'd better test the 1-step request with 1 max_handlers_per_req setting again.
> Because cpuThreadPool has high contention than ioThreadPool for normal requests.

Agreed. I also had this concern. But according to my tests, the 1-step scenario seems no observable degradation.

**Comment by dangleptr** [comment]
> > > With the same client concurrency(28 conn), this PR boosts the QPS from 400 to 800, P99 400ms to 200ms.
> > 
> > 
> > I suggest we'd better test the 1-step request with 1 max_handlers_per_req setting again.
> > Because cpuThreadPool has high contention than ioThreadPool for normal requests.
> 
> Agreed. I also had this concern. But according to my tests, the 1-step scenario seems no observable degradation.

If so,  i am OK with the changes.  
Do you mind share the numbers about your 1-step-1-handler testing here?

@critical27 Maybe we should add the concurrent setting back in 2.0.   :(

**Comment by CPWstatic** [comment]
Maybe we need more test cases to evaluate this improvement.

**Comment by critical27** [comment]
Em, interesting.

**Pull request merged**
