### PR TITLE
update the format of the config yaml of the nba dataset to the latest…

### PR DESCRIPTION
**Pull request by xtcyclist**
… 3.0 version for nebula-importer.

## What type of PR is this?
- [] bug
- [] feature
- [x] enhancement

#### Issue(s) number: 
#4403 

## How do you solve it?
Update format.

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [X] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Comment by Sophie-Xie** [comment]
@xtcyclist plz fix the error of CI, thanks~~

**Comment by Aiee** [comment]
Seems the config yaml is used to load schema at `nebula/nebula/tests/common/utils.py::413`

**Comment by xtcyclist** [comment]
> Seems the config yaml is used to load schema at `nebula/nebula/tests/common/utils.py::413`

yes...

**Comment by xtcyclist** [comment]
the current config file is still in use. close the pr.

**Pull request closed without merging**
