### PR TITLE
Support unreserved keywords.

### PR DESCRIPTION
**Pull request by boshengchen**
refer to issue #327

### CODE REVIEW

**Comment by dutor** [comment]
> >   **I actually thought about it，The yy_destroy_  garbage collector reclaims memory used by objects that can never again be accessed.  And the yy_destroy_  will be executed when the program completes or if there is parse error. I didn't find other memory leaks that might have caused. Could help me analyze it ?**
> 
> ```
>  inline
>   void
>    GraphParser ::yy_destroy_ (const char* yymsg, basic_symbol<Base>& yysym) const
>   {
>     if (yymsg)
>       YY_SYMBOL_PRINT (yymsg, yysym);
> 
>     // User destructor.
>  switch (yysym.type_get ())
>     {
> ......
>       case 118: // name_label
>         { delete (yysym.value.strval); }
>         break;
>       case 119: // unreserved_keyword
>         { delete (yysym.value.strval); }
>         break;
> .......
> }
> ```

The so-called destructor are generated by the `destructor` directives. If I were correct, that will not cover cases here, but I will verify this.

Please hold on for a while.

**Comment by dutor** [comment]
Sorry for the long latency.

I have verify the memory leaks problem mentioned above. It's definitely true.

BTW. This PR is obsolete now because your own fork had been detached with upstream. Could you reopen a new one?

**Comment by boshengchen** [comment]
Sure, let me reopen a PR instead of this one. Wait a moment please.

**Comment by boshengchen** [comment]
Opened a new PR #369. Close this one.

**Comment by boshengchen** [comment]
Opened a new PR #396. Close this one.

**Pull request closed without merging**
