### PR TITLE
Fix slow query test.

### PR DESCRIPTION
**Pull request by CPWstatic**
The rebuild_index job is rate limited now. This makes the test has to wait for much time.

### CODE REVIEW

**Review by bright-starry-sky — DISMISSED** [review]
The slow query test case passed. but another test failed. Let's fix them one by one. 

newly failed:
test_delete_int_vid_one_vertex_all_tag

**Comment by CPWstatic** [comment]
close #2772

**Comment by critical27** [comment]
> The slow query test case passed. but another test failed. Let's fix them one by one.
> 
> newly failed:
> test_delete_int_vid_one_vertex_all_tag

There must be something wrong with the tck test framework when rebuild index speed is slower than expected. I guess it won't appear after #2795 merged.

**Comment by yixinglu** [comment]
> > The slow query test case passed. but another test failed. Let's fix them one by one.
> > newly failed:
> > test_delete_int_vid_one_vertex_all_tag
> 
> There must be something wrong with the tck test framework when rebuild index speed is slower than expected. I guess it won't appear after #2795 merged.

Event if index rebuilding slow down the whole tests, delete tag should be ok. I think we should find out the cause of the failure

**Comment by CPWstatic** [comment]
Fixed by #2795

**Pull request closed without merging**
