### PR TITLE
fix round(5) crash, check type error

### PR DESCRIPTION
**Pull request by leaout**
## What type of PR is this?
- [ ] bug
- [ ] feature
- [ ] enhancement

#### Description:
return round(5) crash

## How do you solve it?
add type check

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Review by Salieri-004 — APPROVED** [review]
Thanks for your contribution!

**Review by codesigner — APPROVED** [review]

**Comment by Salieri-004** [comment]
@leaout Please sign Contributor License Agreement

**Comment by leaout** [comment]
> @leaout Please sign Contributor License Agreement

image
License is ok

**Comment by Salieri-004** [comment]
@leaout  Could you check this page? 
image

**Comment by leaout** [comment]
> @leaout Could you check this page? image

User name And email address had error， first commit message was not to be modified，what should I do？

**Comment by Salieri-004** [comment]
> > @leaout Could you check this page? image
> 
> User name And email address had error， first commit message was not to be modified，what should I do？

Could you roll back and recommit it?

**Pull request merged**
