### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by laura-ding**

### CODE REVIEW

**Comment by laura-ding** [comment]
jenkins go

**Comment by dangleptr** [comment]
Which one build failed?

**Comment by laura-ding** [comment]
@dangleptr 
image

**Comment by darionyaphet** [comment]
I think I've had similar problems.

Could you describe it in detail ?

**Comment by dangleptr** [comment]
@laura-ding Got it.  In multi-process make,  the dependency order should be ensured.

**Comment by laura-ding** [comment]
test

**Pull request merged**
