### PR TITLE
sync from ent repo for supportting show hosts storage listener

### PR DESCRIPTION
**Pull request by panda-sheep**
## What type of PR is this?
- [ ] bug
- [x] feature
- [ ] enhancement

#### Description:
Synchronize from the enterprise version, support the following functions:
image

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Review by critical27 — APPROVED** [review]

**Comment by critical27** [comment]
Involves thrift compactiblity. If no other components use the interface, it is ok.

**Comment by codesigner** [comment]
2 suggestion

**Comment by codesigner** [comment]
Take care when modified the thrift.

**Review by codesigner — APPROVED** [review]
LGTM

**Review by cangfengzhs — APPROVED** [review]

**Pull request merged**
