### PR TITLE
Fix get edges transform rule.

### PR DESCRIPTION
**Pull request by Shylock-Hg**
1. Input/Ouput variables.
2. Keep column names of Limit same with input plan node.

## What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Comment by czpmango** [comment]
Nice fix. But since it is a bug fix, is there a corresponding issue to track? For the current pr, it is also necessary to add test cases to constrain subsequent development.

**Comment by wey-gu** [comment]
> Nice fix. But since it is a bug fix, is there a corresponding issue to track? For the current pr, it is also necessary to add test cases to constrain subsequent development.

Thanks, I would like to learn how some of the fixes (addressing my previous faults I think) cover wrong behaviors, too!
Silly questions

- i.e. I don't understand when should we care about input var, output var, col, and when we don't have to, I need to look into its corresponding nodes' executor code or?
- and, I don't understand why for instance `PushTopN index scan` and `Push vFilter ScanV` are doing erase policy differently(one for current and other for all)

**Comment by Shylock-Hg** [comment]
> Nice fix. But since it is a bug fix, is there any corresponding issue to track? For the current pr, it is also necessary to add test cases to constrain subsequent development.

In fact, the CI job in Debug building will report error, but now it always compile to OOM

**Comment by Shylock-Hg** [comment]
> > Nice fix. But since it is a bug fix, is there a corresponding issue to track? For the current pr, it is also necessary to add test cases to constrain subsequent development.
> 
> Thanks, I would like to learn how some of the fixes (addressing my previous faults I think) cover wrong behaviors, too!
> 
> Silly questions from my side
> 
> * i.e. I don't understand when should we care about input var, output var, col, and when we don't have to, I need to look into its corresponding nodes' executor code or?
> * and, I don't understand why for instance `PushTopN index scan` and `Push vFilter ScanV` are doing erase policy differently(one for current and other for all)

1. You can check the constraints I mentioned in https://github.com/vesoft-inc/nebula/pull/4146#issue-1202863174
2. Now there are no differences, two methods to erase will lead to that subplan produced by rule will replace origin.

**Pull request merged**
