### PR TITLE
[bugfix] security: fix check grant god when FLAGS_enable_authorize is…

### LINKED ISSUE #4684: Shouldn't the cluster have only one account with the God role?
env:
image
When I set `--enable_authorize=flase`, the `God` role can be granted to any account and there can be many accounts with the `God` role. Isn't there only one account with the God role in one cluster?

Suppose that the God role can be granted to many accounts when `--enable_authorize=flase` is set, why cannot we grant the other roles to the accounts with the `God` role?
image

### PR DESCRIPTION
**Pull request by codesigner**
God role should not be granted when enable_authorize is false

2 check was lift up before the FLAGS_enable_authorize check
```
 // Check 1. Reject any user grant or revoke role to GOD,
  if (targetRole == meta::cpp2::RoleType::GOD) {
    return Status::PermissionError("No permission to grant/revoke god user.");
  }

  // Check 2. Cloud auth user cannot grant role
  if (FLAGS_auth_type == "cloud") {
    return Status::PermissionError("Cloud authenticate user can't write role.");
  }

```
Not sure if auth_type cloud should also do this, comment if you know

## What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

#### Issue(s) number: 

fix #4684 

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Comment by Shylock-Hg** [comment]
Plz add test case.

**Comment by codesigner** [comment]
> Plz add test case.

Is there a way to set FLAGS_enable_authorize when run TCK?

**Comment by Shylock-Hg** [comment]
> > Plz add test case.
> 
> Is there a way to set FLAGS_enable_authorize when run TCK?

Could disable one runner, https://github.com/vesoft-inc/nebula/blob/master/tests/common/nebula_service.py

**Comment by codesigner** [comment]
> disable

OK, let me try it

**Comment by Aiee** [comment]
@MegaByte875 Please verify this change won't affect any current behavior in cloud products.

**Comment by MegaByte875** [comment]
@Aiee It's ok, no problem.

**Review by Shylock-Hg — APPROVED** [review]

**Review by jievince — APPROVED** [review]

**Pull request merged**
