### PR TITLE
showIndexByID

### PR DESCRIPTION
**Pull request by sworduo**
## What type of PR is this?
- [ ] bug
- [ ] feature
- [☑️] enhancement

#### Issue(s) number: 
related to https://github.com/vesoft-inc/nebula/issues/4320
## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Comment by Shylock-Hg** [comment]
Please add test in `tests` folder.

**Comment by Shylock-Hg** [comment]
> > Please add test in `tests` folder.
> 
> How can I get indexID except explain expression? Or could I make an assumption that the indexID of space `nba` loading by `make up` in tests are fixed?

I'm not sure why you added this PR, but in our design, we don't intend to expose any `ID` of schema.

**Comment by sworduo** [comment]
> we don't intend to expose

For example, in production, a tag may contain 20~30 fields, and the number of associated indexes may near 100 (I have no idea why they need so much, but they did). When we use explain expression to analyze the ngql, it's hard to find the corresponding index by indexID exposed in indexCtx.

**Comment by Shylock-Hg** [comment]
> > we don't intend to expose
> 
> For example, in production, a tag may contain 20~30 fields, and the number of associated indexes may near 100 (I have no idea why they need so much, but they did). When we use explain expression to analyze the ngql, it's hard to find the corresponding index by indexID exposed in indexCtx.

Ok, but we'd better to expose the name of id in explain. If you don't plan to pull request it, could create a issue.

**Comment by sworduo** [comment]
> > > we don't intend to expose
> > 
> > 
> > For example, in production, a tag may contain 20~30 fields, and the number of associated indexes may near 100 (I have no idea why they need so much, but they did). When we use explain expression to analyze the ngql, it's hard to find the corresponding index by indexID exposed in indexCtx.
> 
> Ok, but we'd better to expose the name of id in explain. If you don't plan to pull request it, could create a issue.

That's ok. But should the id of space/tag/edge/index expose in explain any more? Or we just illustrate the name of space/tag/edge/index in explain expression.

**Comment by Shylock-Hg** [comment]
> > > > we don't intend to expose
> > > 
> > > 
> > > For example, in production, a tag may contain 20~30 fields, and the number of associated indexes may near 100 (I have no idea why they need so much, but they did). When we use explain expression to analyze the ngql, it's hard to find the corresponding index by indexID exposed in indexCtx.
> > 
> > 
> > Ok, but we'd better to expose the name of id in explain. If you don't plan to pull request it, could create a issue.
> 
> That's ok. But should the id of space/tag/edge/index expose in explain any more? Or we just illustrate the name of space/tag/edge/index in explain expression.

Both is better.

**Comment by xtcyclist** [comment]
An conclusion has been reached that internal representations shall not be exposed via nGQL. Thus, I close this PR. In #4320, we can discuss more on how to improve the display of indexes.

**Pull request closed without merging**
