### PR TITLE
meta client thread local access.

### PR DESCRIPTION
**Pull request by xuguruogu**
use thread local object when access meta client cache. folly::SingletonThreadLocal supply efficient access wrapper by using pointer.

### CODE REVIEW

**Comment by xuguruogu** [comment]
the issue came from compaction.

before the changes:
image

after the changes:
image

**Comment by dutor** [comment]
Thanks for this improvement. I also noticed this issue recently, and did some similar optimization. Many other modules may benefit from this patch.

**Comment by dangleptr** [comment]
Please recheck the Failed UTs

**Comment by xuguruogu** [comment]
centos7 unit tests is killed. may due to make oom

**Pull request merged**
