### PR TITLE
Show Create Tag and Edge

### PR DESCRIPTION
**Pull request by darionyaphet**
```
nebula> show create tag player
===========================================
|                                 Command |
===========================================
| CREATE TAG player(name string, age int) |
-------------------------------------------
Got 1 rows (Time spent: 189/915 us)

nebula> show create edge serve
===================================================
|                                         Command |
===================================================
| CREATE EDGE serve(start_year int, end_year int) |
---------------------------------------------------
Got 1 rows (Time spent: 167/965 us)
```

### CODE REVIEW

**Comment by steppenwolfyuetong** [comment]
`Support show create tag/edge xxx, show create space xxx SQL #439`  has implement In pr `#497`

By the way, this is not the function I expected.

**Comment by dangleptr** [comment]
duplicate with #496 ?

**Comment by steppenwolfyuetong** [comment]
> duplicate with #496 ?

Yeah, duplicate with #496,  refer Issue #439  `Support show create tag/edge xxx, show create space xxx SQL `
 
This PR is also not what I expected because there is no intention to Issue PR #439

**Comment by dangleptr** [comment]
> > duplicate with #496 ?
> 
> Yeah, duplicate with #496, refer Issue #439 `Support show create tag/edge xxx, show create space xxx SQL `
> 
> This PR is also not what I expected because there is no intention to Issue PR #439

If so, please abandon it and give your review comments in #496   @darionyaphet

**Pull request closed without merging**
