### PR TITLE
Migrate download and ingest into job manager

### PR DESCRIPTION
**Pull request by darionyaphet**
## What type of PR is this?
- [ ] bug
- [ ] feature
- [*] enhancement

#### Issue(s) number: 
https://github.com/vesoft-inc/nebula/issues/3733

#### Description:

```
SUBMIT COMMAND:

(root@nebula) [test]> FETCH PROP ON t 1 YIELD t.name
+--------+
| t.name |
+--------+
+--------+
Empty set (time spent 5474/6039 us)

Sun, 27 Mar 2022 07:39:34 CST

(root@nebula) [test]> SUBMIT JOB DOWNLOAD HDFS "hdfs://192.168.8.215:9000/tmp"
+------------+
| New Job Id |
+------------+
| 10         |
+------------+
Got 1 rows (time spent 2800/3514 us)

Sun, 27 Mar 2022 07:39:48 CST

(root@nebula) [test]> show jobs
+--------+------------+------------+----------------------------+----------------------------+
| Job Id | Command    | Status     | Start Time                 | Stop Time                  |
+--------+------------+------------+----------------------------+----------------------------+
| 10     | "DOWNLOAD" | "FINISHED" | 2022-03-26T23:39:48.000000 | 2022-03-26T23:39:52.000000 |
| 9      | "INGEST"   | "FINISHED" | 2022-03-26T16:42:44.000000 | 2022-03-26T16:42:44.000000 |
| 8      | "DOWNLOAD" | "FINISHED" | 2022-03-26T15:33:08.000000 | 2022-03-26T15:33:12.000000 |
| 7      | "INGEST"   | "FINISHED" | 2022-03-26T15:32:34.000000 | 2022-03-26T15:32:34.000000 |
| 6      | "INGEST"   | "FINISHED" | 2022-03-26T15:22:30.000000 | 2022-03-26T15:22:30.000000 |
| 5      | "DOWNLOAD" | "FINISHED" | 2022-03-26T15:22:16.000000 | 2022-03-26T15:22:21.000000 |
| 4      | "INGEST"   | "FINISHED" | 2022-03-26T15:13:46.000000 | 2022-03-26T15:13:46.000000 |
| 3      | "DOWNLOAD" | "FINISHED" | 2022-03-26T15:13:35.000000 | 2022-03-26T15:13:39.000000 |
+--------+------------+------------+----------------------------+----------------------------+
Got 8 rows (time spent 3269/4888 us)

Sun, 27 Mar 2022 07:39:54 CST

(root@nebula) [test]> SUBMIT JOB INGEST
+------------+
| New Job Id |
+------------+
| 11         |
+------------+
Got 1 rows (time spent 3055/3962 us)

Sun, 27 Mar 2022 07:40:04 CST

(root@nebula) [test]> show jobs
+--------+------------+------------+----------------------------+----------------------------+
| Job Id | Command    | Status     | Start Time                 | Stop Time                  |
+--------+------------+------------+----------------------------+----------------------------+
| 11     | "INGEST"   | "FINISHED" | 2022-03-26T23:40:04.000000 | 2022-03-26T23:40:04.000000 |
| 10     | "DOWNLOAD" | "FINISHED" | 2022-03-26T23:39:48.000000 | 2022-03-26T23:39:52.000000 |
| 9      | "INGEST"   | "FINISHED" | 2022-03-26T16:42:44.000000 | 2022-03-26T16:42:44.000000 |
| 8      | "DOWNLOAD" | "FINISHED" | 2022-03-26T15:33:08.000000 | 2022-03-26T15:33:12.000000 |
| 7      | "INGEST"   | "FINISHED" | 2022-03-26T15:32:34.000000 | 2022-03-26T15:32:34.000000 |
| 6      | "INGEST"   | "FINISHED" | 2022-03-26T15:22:30.000000 | 2022-03-26T15:22:30.000000 |
| 5      | "DOWNLOAD" | "FINISHED" | 2022-03-26T15:22:16.000000 | 2022-03-26T15:22:21.000000 |
| 4      | "INGEST"   | "FINISHED" | 2022-03-26T15:13:46.000000 | 2022-03-26T15:13:46.000000 |
| 3      | "DOWNLOAD" | "FINISHED" | 2022-03-26T15:13:35.000000 | 2022-03-26T15:13:39.000000 |
+--------+------------+------------+----------------------------+----------------------------+
Got 9 rows (time spent 2957/4441 us)

Sun, 27 Mar 2022 07:40:06 CST

(root@nebula) [test]> FETCH PROP ON t 1 YIELD t.name
+-----------+
| t.name    |
+-----------+
| "darion1" |
+-----------+
Got 1 rows (time spent 4353/5023 us)

Sun, 27 Mar 2022 07:40:09 CST



---------------------------------------------------------------------------------------------------------
DOWNLOAD AND INGEST COMMAND:

(root@nebula) [test]> FETCH PROP ON t 1 YIELD t.name
+--------+
| t.name |
+--------+
+--------+
Empty set (time spent 5332/6180 us)

Sun, 27 Mar 2022 07:41:39 CST

(root@nebula) [test]> DOWNLOAD HDFS "hdfs://192.168.8.215:9000/tmp"
+------------+
| New Job Id |
+------------+
| 12         |
+------------+
Got 1 rows (time spent 3028/3785 us)

Sun, 27 Mar 2022 07:41:59 CST

(root@nebula) [test]> show jobs
+--------+------------+------------+----------------------------+----------------------------+
| Job Id | Command    | Status     | Start Time                 | Stop Time                  |
+--------+------------+------------+----------------------------+----------------------------+
| 12     | "DOWNLOAD" | "FINISHED" | 2022-03-26T23:41:59.000000 | 2022-03-26T23:42:03.000000 |
| 11     | "INGEST"   | "FINISHED" | 2022-03-26T23:40:04.000000 | 2022-03-26T23:40:04.000000 |
| 10     | "DOWNLOAD" | "FINISHED" | 2022-03-26T23:39:48.000000 | 2022-03-26T23:39:52.000000 |
| 9      | "INGEST"   | "FINISHED" | 2022-03-26T16:42:44.000000 | 2022-03-26T16:42:44.000000 |
| 8      | "DOWNLOAD" | "FINISHED" | 2022-03-26T15:33:08.000000 | 2022-03-26T15:33:12.000000 |
| 7      | "INGEST"   | "FINISHED" | 2022-03-26T15:32:34.000000 | 2022-03-26T15:32:34.000000 |
| 6      | "INGEST"   | "FINISHED" | 2022-03-26T15:22:30.000000 | 2022-03-26T15:22:30.000000 |
| 5      | "DOWNLOAD" | "FINISHED" | 2022-03-26T15:22:16.000000 | 2022-03-26T15:22:21.000000 |
| 4      | "INGEST"   | "FINISHED" | 2022-03-26T15:13:46.000000 | 2022-03-26T15:13:46.000000 |
| 3      | "DOWNLOAD" | "FINISHED" | 2022-03-26T15:13:35.000000 | 2022-03-26T15:13:39.000000 |
+--------+------------+------------+----------------------------+----------------------------+
Got 10 rows (time spent 3408/4976 us)

Sun, 27 Mar 2022 07:42:17 CST

(root@nebula) [test]> INGEST
+------------+
| New Job Id |
+------------+
| 13         |
+------------+
Got 1 rows (time spent 2641/3205 us)

Sun, 27 Mar 2022 07:42:21 CST

(root@nebula) [test]> show jobs
+--------+------------+------------+----------------------------+----------------------------+
| Job Id | Command    | Status     | Start Time                 | Stop Time                  |
+--------+------------+------------+----------------------------+----------------------------+
| 13     | "INGEST"   | "FINISHED" | 2022-03-26T23:42:21.000000 | 2022-03-26T23:42:21.000000 |
| 12     | "DOWNLOAD" | "FINISHED" | 2022-03-26T23:41:59.000000 | 2022-03-26T23:42:03.000000 |
| 11     | "INGEST"   | "FINISHED" | 2022-03-26T23:40:04.000000 | 2022-03-26T23:40:04.000000 |
| 10     | "DOWNLOAD" | "FINISHED" | 2022-03-26T23:39:48.000000 | 2022-03-26T23:39:52.000000 |
| 9      | "INGEST"   | "FINISHED" | 2022-03-26T16:42:44.000000 | 2022-03-26T16:42:44.000000 |
| 8      | "DOWNLOAD" | "FINISHED" | 2022-03-26T15:33:08.000000 | 2022-03-26T15:33:12.000000 |
| 7      | "INGEST"   | "FINISHED" | 2022-03-26T15:32:34.000000 | 2022-03-26T15:32:34.000000 |
| 6      | "INGEST"   | "FINISHED" | 2022-03-26T15:22:30.000000 | 2022-03-26T15:22:30.000000 |
| 5      | "DOWNLOAD" | "FINISHED" | 2022-03-26T15:22:16.000000 | 2022-03-26T15:22:21.000000 |
| 4      | "INGEST"   | "FINISHED" | 2022-03-26T15:13:46.000000 | 2022-03-26T15:13:46.000000 |
| 3      | "DOWNLOAD" | "FINISHED" | 2022-03-26T15:13:35.000000 | 2022-03-26T15:13:39.000000 |
+--------+------------+------------+----------------------------+----------------------------+
Got 11 rows (time spent 2864/4388 us)

Sun, 27 Mar 2022 07:42:23 CST

(root@nebula) [test]> FETCH PROP ON t 1 YIELD t.name
+-----------+
| t.name    |
+-----------+
| "darion1" |
+-----------+
Got 1 rows (time spent 4644/5267 us)

Sun, 27 Mar 2022 07:42:25 CST


```
## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Comment by panda-sheep** [comment]
please fix conflicts

**Review by critical27 — COMMENTED** [review]
Generally LGTM, support ingest concurrently of different engines.

**Comment by HarrisChu** [comment]
BTW, after this pr, no need configuration for `ws_meta_http_port` in graphd and `ws_storage_port` in metad
am I right?

**Comment by darionyaphet** [comment]
> BTW, after this pr, no need configuration for `ws_meta_http_port` in graphd and `ws_storage_port` in metad am I right?

no  `ReplaceHost` still use it

**Comment by HarrisChu** [comment]
> > BTW, after this pr, no need configuration for `ws_meta_http_port` in graphd and `ws_storage_port` in metad am I right?
> 
> no `ReplaceHost` still use it

OK 👌🏻

**Comment by critical27** [comment]
> > BTW, after this pr, no need configuration for `ws_meta_http_port` in graphd and `ws_storage_port` in metad am I right?
> 
> no `ReplaceHost` still use it

We don't need `ws_meta_http_port`/`ws_storage_port`? ReplaceHost is a pure http interface...

**Comment by darionyaphet** [comment]
> > > BTW, after this pr, no need configuration for `ws_meta_http_port` in graphd and `ws_storage_port` in metad am I right?
> > 
> > 
> > no `ReplaceHost` still use it
> 
> We don't need `ws_meta_http_port`/`ws_storage_port`? ReplaceHost is a pure http interface...

`replace` register on web service router

**Comment by darionyaphet** [comment]
> > > BTW, after this pr, no need configuration for `ws_meta_http_port` in graphd and `ws_storage_port` in metad am I right?
> > 
> > 
> > no `ReplaceHost` still use it
> 
> We don't need `ws_meta_http_port`/`ws_storage_port`? ReplaceHost is a pure http interface...

`replace` method is register on  http web service router

**Review by liuyu85cn — APPROVED** [review]

**Review by panda-sheep — APPROVED** [review]

**Review by CPWstatic — APPROVED** [review]

**Pull request merged**
