### PR TITLE
optimize find path

### PR DESCRIPTION
**Pull request by nevermore3**
## What type of PR is this?
- [ ] bug
- [ ] feature
- [x] enhancement

#### Description:
1、Optimize memory usage
2、Simplify the algorithm，please refer to the code comments for details

## Checklist:
Tests:
- [x] Unit test(positive and negative cases)
- [ ] Function test
- [x] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Comment by Shylock-Hg** [comment]
Do you have benchmark about speed and memory improvement?

**Comment by Shylock-Hg** [comment]
Do you have benchmark about speed and memory improvement?

**Comment by nevermore3** [comment]
> Do you have benchmark about speed and memory improvement?


the stress test tool does not support Find Path yet, 
memory optimization is the previous version saved all paths, now only the path of the previous step is saved

**Comment by nevermore3** [comment]
> > Do you have benchmark about speed and memory improvement?
> 
> the stress test tool does not support Find Path yet, memory optimization is the previous version saved all paths, now only the path of the previous step is saved

**Comment by nevermore3** [comment]
refer to https://github.com/vesoft-inc/nebula/pull/4095

**Pull request closed without merging**
