### PR TITLE
UDF based on existing function infra

### LINKED ISSUE #5337: Support user-defined functions
https://github.com/vesoft-inc/nebula/discussions/4793

### PR DESCRIPTION
**Pull request by zhaojunnana**
## What type of PR is this?
- [ ] bug
- [x] feature
- [ ] enhancement

#### Issue(s) number: 
https://github.com/vesoft-inc/nebula/discussions/4793
Close #5337

#### Description:
Users can define functions by implementing GraphFunction

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [x] Documentation affected (Please add the label if documentation needs to be modified.)
    see https://github.com/vesoft-inc/nebula/pull/4804/#issuecomment-1427318108
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Comment by wey-gu** [comment]
@zhaojunnana I added an example of building the UDF, based on some downstream work from @xtcyclist , too.

Nice job, we tested it worked like a charm :)

@xtcyclist g++ used to enable redhat distributions to build, too.

**Comment by wey-gu** [comment]
Docs:


---------------
### 编译环境准备，参考

- https://docs.nebula-graph.com.cn/3.3.0/4.deployment-and-installation/1.resource-preparations/#_6
- https://docs.nebula-graph.com.cn/3.3.0/4.deployment-and-installation/2.compile-and-install-nebula-graph/1.install-nebula-graph-by-compiling-the-source-code/



### 进入到代码仓库，定义编写 UDF

```bash
$ tree udf
udf
|-- Makefile
|-- standard_deviation.cpp
`-- standard_deviation.h

```

这里我们实现一个求给定数组的方差的函数：

`standard_deviation.h`里的代码：

```c++
#ifndef UDF_PROJECT_STANDARD_DEVIATION_H
#define UDF_PROJECT_STANDARD_DEVIATION_H

#include "../src/common/function/GraphFunction.h"

class standard_deviation : public GraphFunction {
 public:
  char *name() override;

  std::vector<std::vector<nebula::Value::Type>> inputType() override;

  nebula::Value::Type returnType() override;

  size_t minArity() override;

  size_t maxArity() override;

  bool isPure() override;

  nebula::Value body(const std::vector<std::reference_wrapper<const nebula::Value>> &args) override;
};

#endif  // UDF_PROJECT_STANDARD_DEVIATION_H
```

`standard_deviation.cpp`里的代码：

```c++
/* Copyright (c) 2020 vesoft inc. All rights reserved.
 *
 * This source code is licensed under Apache 2.0 License.
 */

#include <cmath>
#include <vector>

#include "standard_deviation.h"

#include "../src/common/datatypes/List.h"
#include "../src/common/datatypes/Value.h"

extern "C" GraphFunction *create() {
  return new standard_deviation;
}
extern "C" void destroy(GraphFunction *function) {
  delete function;
}

char *standard_deviation::name() {
  const char *name = "standard_deviation";
  return const_cast<char *>(name);
}

std::vector<std::vector<nebula::Value::Type>> standard_deviation::inputType() {
  std::vector<nebula::Value::Type> vtp = {nebula::Value::Type::LIST};
  std::vector<std::vector<nebula::Value::Type>> vvtp = {vtp};
  return vvtp;
}

nebula::Value::Type standard_deviation::returnType() {
  return nebula::Value::Type::FLOAT;
}

size_t standard_deviation::minArity() {
  return 1;
}

size_t standard_deviation::maxArity() {
  return 1;
}

bool standard_deviation::isPure() {
  return true;
}

double standardDeviation(const std::vector<double> &numbers) {
    double sum = 0;
    for (double number : numbers) {
        sum += number;
    }
    double average = sum / numbers.size();

    double variance = 0;
    for (double number : numbers) {
        double difference = number - average;
        variance += difference * difference;
    }
    variance /= numbers.size();

    return sqrt(variance);
}

nebula::Value standard_deviation::body(
    const std::vector<std::reference_wrapper<const nebula::Value>> &args) {
  switch (args[0].get().type()) {
    case nebula::Value::Type::NULLVALUE: {
      return nebula::Value::kNullValue;
    }
    case nebula::Value::Type::LIST: {
      std::vector<double> numbers;
      auto list = args[0].get().getList();
      auto size = list.size();

      for (int i = 0; i < size; i++) {
        auto &value = list[i];
        if (value.isInt()) {
          numbers.push_back(value.getInt());
        } else if (value.isFloat()) {
          numbers.push_back(value.getFloat());
        } else {
          return nebula::Value::kNullValue;
        }
      }
      return nebula::Value(standardDeviation(numbers));
    }
    default: {
      return nebula::Value::kNullValue;
    }
  }
}
```

然后编译：

```bash
$ cd udf; make
clang++-10 ./standard_deviation.cpp -c -o standard_deviation.o -I ../src/ -fPIC -I ../build/third-party/install/include/
clang++-10 -shared -o standard_deviation.so standard_deviation.o
```

这时候，文件被编译成二进制 `.so`，如下：

```bash
$ tree .
.
|-- Makefile
|-- standard_deviation.cpp
|-- standard_deviation.h
|-- standard_deviation.o
`-- standard_deviation.so
```



### 加载 UDF 到 GraphD

假设我们把代码仓库放到 `/home/foobar/dev/nebula/` 下边，udf 代码放在其中的 `udf` 目录，修改需要加载 UDF 的 graphd 配置

```bash
$ tail /usr/local/nebula/etc/nebula-graphd.conf -n 5

# enable udf, c++ only
--enable_udf=true
# set the directory where the .so of udf are stored
--udf_path=/home/foobar/dev/nebula/udf/
```

重启 graphd

```bash
sudo /usr/local/nebula/scripts/nebula.service restart graphd
```

### 测试 UDF

连接到重启的 GraphD, 测试 `standard_deviation` 函数：

```bash
$ nebula-console-3.0 -addr 127.0.0.1  -port 9669 -user root -p nebula

(root@nebula) [(none)]> yield standard_deviation([1,2,3])
+-----------------------------+
| standard_deviation([1,2,3]) |
+-----------------------------+
| 0.816496580927726           |
+-----------------------------+
Got 1 rows (time spent 9944/18471 us)

(root@nebula) [(none)]> yield standard_deviation([1,1,1])
+-----------------------------+
| standard_deviation([1,1,1]) |
+-----------------------------+
| 0.0                         |
+-----------------------------+
Got 1 rows (time spent 4559/12630 us)

Fri, 03 Feb 2023 16:11:24 CST

(root@nebula) [basketballplayer]> GO 1 TO 2 STEPS FROM "player100" OVER follow YIELD properties(edge).degree AS d | yield collect($-.d)
+--------------------------+
| collect($-.d)            |
+--------------------------+
| [95, 95, 95, 90, 95, 90] |
+--------------------------+
Got 1 rows (time spent 6424/14165 us)

Fri, 03 Feb 2023 16:12:05 CST

(root@nebula) [basketballplayer]> GO 1 TO 2 STEPS FROM "player100" OVER follow YIELD properties(edge).degree AS d | yield collect($-.d) AS d | yield standard_deviation($-.d)
+--------------------------+
| standard_deviation($-.d) |
+--------------------------+
| 2.357022603955158        |
+--------------------------+
Got 1 rows (time spent 9809/15682 us)
```

**Review by xtcyclist — APPROVED** [review]
This contribution on udf is very much appreciated.

**Review by jievince — APPROVED** [review]
Good job

**Comment by wey-gu** [comment]
Thanks a lot @zhaojunnana !

**Comment by wey-gu** [comment]
@abby-cyber 发现我用错了名字，我给的例子是标准差，不是方差，我已经编辑了，另外就是如电话说的， make 的部分参考最新的pr

**Pull request merged**
