### PR TITLE
To link executables with -no-pie

### PR DESCRIPTION
**Pull request by dutor**
Some compilers are built with `-enable-default-pie`. That is no problem generally, but glog is buggy to deal with this when retrieve the backtrace. So we disable pie from our own side.

### CODE REVIEW

**Comment by monadbobo** [comment]
Could you describe the problem caused by glog in more detail?

**Comment by dutor** [comment]
> Could you describe the problem caused by glog in more detail?

Actually, glog introduced a bug that will cause the symbol resolve fail for PIE, which is exactly the version we are currently using, which has been fixed the the latest release.

**Comment by steppenwolfyuetong** [comment]
> > Could you describe the problem caused by glog in more detail?
> 
> Actually, glog introduced a bug that will cause the symbol resolve fail for PIE, which is exactly the version we are currently using, which has been fixed the the latest release.

@dutor   I have a question, why not use the latest version of glog ?

**Comment by dutor** [comment]
> > > Could you describe the problem caused by glog in more detail?
> > 
> > 
> > Actually, glog introduced a bug that will cause the symbol resolve fail for PIE, which is exactly the version we are currently using, which has been fixed the the latest release.
> 
> @dutor I have a question, why not use the latest version of glog ?

First, it makes little sense to us to enable PIE, by default. Second, we should try our best to reduce mandatory requirements on our dependencies, especially when we have better options to deal with the problems.

FYI. we are going to move the third-party out from our repo.

**Comment by steppenwolfyuetong** [comment]
> > > > Could you describe the problem caused by glog in more detail?
> > > 
> > > 
> > > Actually, glog introduced a bug that will cause the symbol resolve fail for PIE, which is exactly the version we are currently using, which has been fixed the the latest release.
> > 
> > 
> > @dutor I have a question, why not use the latest version of glog ?
> 
> First, it makes little sense to us to enable PIE, by default. Second, we should try our best to reduce mandatory requirements on our dependencies, especially when we have better options to deal with the problems.
> 
> FYI. we are going to move the third-party out from our repo.

f1634089a5014f20919a619ed3eb2e2e

**Comment by monadbobo** [comment]
LGTM!

**Pull request merged**
