### PR TITLE
Refactor storage::RelNode constructors

### PR DESCRIPTION
**Pull request by yixinglu**
* Use initializer list to init `name` field of `storage::RelNode`. 
* Pull the RuntimeContext upto the QueryNode class
* minor improvement of the go validator implementation

### CODE REVIEW

**Comment by bright-starry-sky** [comment]
What is the real purpose of this PR?

**Comment by bright-starry-sky** [comment]
> What is the real purpose of this PR?

for execute plan of storage profile ?

**Comment by yixinglu** [comment]
> > What is the real purpose of this PR?
> 
> for execute plan of storage profile ?

Don't change any logic, just clean up some implementations that I think are not good

**Review by jievince — APPROVED** [review]
Well done! Makes the code more clear!

**Comment by cangfengzhs** [comment]
Lookup index in storage has been refactor.

**Pull request closed without merging**
