### PR TITLE
Fix the download path for ingest

### PR DESCRIPTION
**Pull request by darionyaphet**

### CODE REVIEW

**Comment by dangleptr** [comment]
Jenkins go

**Comment by darionyaphet** [comment]
jenkins go

**Comment by whitewum** [comment]
Great. Is it necessary to write a simple manual (.md) for this operation?

**Comment by dutor** [comment]
Jenkins go

**Comment by dutor** [comment]
Jenkins go

**Comment by darionyaphet** [comment]
jenkins go

**Pull request merged**
