### PR TITLE
Push dowm filter

### PR DESCRIPTION
**Pull request by zhaojunnana**
## What type of PR is this?
- [ ] bug
- [ ] feature
- [x] enhancement

#### Description:
Push down all possible filters for GetNeighbors

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Comment by xtcyclist** [comment]
I think we should try merging this PR to `master`? @Sophie-Xie right?

**Comment by wey-gu** [comment]
> I think we should try merging this PR to `master` first? @Sophie-Xie right?

@zhaojunnana could you change the merge target into master instead of such base, all PR should go to master.

**Comment by zhaojunnana** [comment]
@wey-gu   The master branch does not compile successfully. There are other problems

**Comment by xtcyclist** [comment]
> @wey-gu The master branch does not compile successfully. There are other problems

Hi. It's ok if there were build issues. We could help addressing them, if needed. After this PR is diverted to `master`, we would be able to see the build issues as well as other testing issues, if any, in this PR thread.

**Comment by wey-gu** [comment]
> @wey-gu The master branch does not compile successfully. There are other problems

Yes as @xtcyclist suggested, it's ok if some rebase adaption work is still needed, that could be done later and we could help when needed.

**Comment by zhaojunnana** [comment]
ok,I have a new pr https://github.com/vesoft-inc/nebula/pull/4805

**Pull request closed without merging**
