### PR TITLE
If user does not exist `desc user xxx` will be raise "User not existed!"

### LINKED ISSUE #5141: Desc not existed user should report error
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

Found in https://github.com/vesoft-inc/nebula/pull/5139

**Your Environments (__required__)**

* OS: `uname -a`
* Compiler: `g++ --version` or `clang++ --version`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by Milittle**
If user does not exist `desc user xxx` will be raise "User not existed!"

## What type of PR is this?
- [x] bug
- [ ] feature
- [x] enhancement

#### Issue(s) number: 
Close #5141

#### Description:
If use does not exist `desc user xxx` will be raise "User not existed!"

## How do you solve it?
add account exist verify in meta service

## Checklist:
Tests:
manunal test:
```
(root@nebula) [(none)]> desc user u6
[ERROR (-1005)]: User not existed!

Wed, 15 Feb 2023 22:43:06 CST
```
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Comment by Milittle** [comment]
if have any problem, leave message here, thanks.

**Comment by Sophie-Xie** [comment]
> if have any problem, leave message here, thanks.
> 
> May i need change my git account. wait me fix this.

Thanks for contribution! Pls fix the CI when your account is OK. :)

**Comment by Milittle** [comment]
> > if have any problem, leave message here, thanks.
> > May i need change my git account. wait me fix this.
> 
> Thanks for contribution! Pls fix the CI when your account is OK. :)



> 

Done

**Review by SuperYoko — APPROVED** [review]

**Review by yixinglu — APPROVED** [review]
Good Job!

**Pull request merged**
