### PR TITLE
fsync upon closing WAL files

### PR DESCRIPTION
**Pull request by lilydjwg**
Or there will be possible data loss / corruption depending on the exact way how data is interpreted and handled. `close` doesn't mean automatic `fsync`.

### CODE REVIEW

**Comment by dutor** [comment]
Thanks for this contribution.

Jenkins, please run tests.

**Comment by dutor** [comment]
Jenkins, please run tests.

**Comment by dangleptr** [comment]
Jenkins go

**Comment by sherman-the-tank** [comment]
jenkins go

**Pull request merged**
