### PR TITLE
tck test cluster

### PR DESCRIPTION
**Pull request by HarrisChu**
#### What type of PR is this?
- [ ] bug
- [ ] feature
- [ x ] enhancement

#### What does this PR do?
enhance tck test framework, testing nebula cluster with 3 storaged.

#### Checklist：
- [ ] Documentation affected （Please add the label if documentation needs to be modified.)
- [ ] Incompatible （If it is incompatible, please describe it and add corresponding label.）
- [ ] Need to cherry-pick （If need to cherry-pick to some branches, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

#### Release notes：
Please confirm whether to reflect in release notes and how to describe:
>                                                                 `

### CODE REVIEW

**Comment by HarrisChu** [comment]
have done:
1. change default nebula cluster with 3 storaged, and then run original tck test cases.
2. fix some features running in 3 storaged.

to be continued:
1. migrate test cases for zone.
2. migrate job feature with a normal test feature?

**Comment by Shylock-Hg** [comment]
We should test single host and cluster together.

**Comment by HarrisChu** [comment]
> We should test single host and cluster together.

yes, just set the default Nebula as a cluster, and can test a single host at the case level.
e.g.
`Given a nebulacluster with 1 graphd and 1 metad and 1 storaged`

**Comment by HarrisChu** [comment]
inspired by https://github.com/vesoft-inc/nebula/pull/3252

**Review by yixinglu — COMMENTED** [review]
Great starting point for cluster testing.

**Review by yixinglu — APPROVED** [review]
LGTM

**Review by CPWstatic — APPROVED** [review]

**Pull request merged**
