### PR TITLE
fix_batch_insert_problem

### PR DESCRIPTION
**Pull request by nevermore3**
#### What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

#### What problem(s) does this PR solve?
Issue(s) number: 

close https://github.com/vesoft-inc/nebula/issues/3193

Description:

#### Checklist:
Tests:
- [x] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [x] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

#### Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Comment by yixinglu** [comment]
need tests

**Comment by nevermore3** [comment]
> need tests

done

**Comment by cangfengzhs** [comment]
I modify some tck test in LookUp.feature at [PR3196](https://github.com/vesoft-inc/nebula/pull/3196/files#diff-6bc21167bc09d8be0a76ab52422a93f4b8b0dd2c5ae729d6a6097bd373dc6244) because of this bug. Maybe you can modify it back now.

**Comment by nevermore3** [comment]
> I modify some tck test in LookUp.feature at [PR3196](https://github.com/vesoft-inc/nebula/pull/3196/files#diff-6bc21167bc09d8be0a76ab52422a93f4b8b0dd2c5ae729d6a6097bd373dc6244) because of this bug. Maybe you can modify it back now.

ok

**Review by yixinglu — APPROVED** [review]

**Review by cangfengzhs — APPROVED** [review]
LGTM

**Pull request merged**
