### PR TITLE
Remove some configs which be dynamic configured

### PR DESCRIPTION
**Pull request by knightXun**

### CODE REVIEW

**Comment by knightXun** [comment]
cc @dutor @laura-ding we must limit dynamic configures in cloud-version

**Comment by yixinglu** [comment]
Why not to give another flags.json for cloud version ?

**Comment by knightXun** [comment]
> I think we may need some discussion offline about how to maintain the cloud version configuration.

agree

**Comment by Shylock-Hg** [comment]
> Why not to give another flags.json for cloud version ?

Agree, I don't think make too many difference between cloud and master branch is better.

**Comment by dangleptr** [comment]
If you want to change the gflags.json in your cluster.  You'd better change it directly and don't commit them into master.

**Pull request closed without merging**
