### PR TITLE
delete src/common/encryption src/common/base/stringunorderedmap

### PR DESCRIPTION
**Pull request by jiayuehua**
## What type of PR is this?
- [ ] bug
- [ ] feature
- [*] enhancement

#### Description:
delete src/common/encryption 

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Comment by Aiee** [comment]
Please check the `license.h` in the enterprise version to verify if this change is compatible.

**Comment by jiayuehua** [comment]
> 



> Please check the `license.h` in the enterprise version to verify if this change is compatible.

https://github.com/vesoft-inc/nebula-ent/blob/master/src/common/encryption/License.h?

**Comment by Aiee** [comment]
> > 
> 
> > Please check the `license.h` in the enterprise version to verify if this change is compatible.
> 
> https://github.com/vesoft-inc/nebula-ent/blob/master/src/common/encryption/License.h?

Yes, some of the methods in `encryption` module is used in license validation, please check `license.cpp`

**Review by Aiee — APPROVED** [review]

**Review by czpmango — APPROVED** [review]

**Comment by jiayuehua** [comment]
https://github.com/vesoft-inc/nebula/issues/3774

**Pull request merged**
