### PR TITLE
Fix meta's cleanup

### PR DESCRIPTION
**Pull request by luyade**
## What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

#### Issue(s) number: 
https://github.com/vesoft-inc/nebula/issues/5320

#### Description:
The meta cleanup forgot to remove system commit id/term.

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

### CODE REVIEW

**Comment by pengweisong** [comment]
Please first open an issue describe the bug, then link it in this pr.

**Comment by luyade** [comment]
> Please first open an issue to describe the bug, then link it in this pr.

This can be part of the change to address the issue in https://github.com/vesoft-inc/nebula/issues/5320. It seems in https://github.com/vesoft-inc/nebula/pull/5321 we forgot to clean the metad's commit it/term.

**Review by critical27 — APPROVED** [review]
Good job

**Review by pengweisong — APPROVED** [review]
Good job

**Pull request merged**
