### PR TITLE
fix wrong image path for architecture

### PR DESCRIPTION
**Pull request by TommyLemon**
the original image path "https://github.com/vesoft-inc/nebula-docs/raw/master/images/Nebula%20Arch.png" is outdated and cannot be loaded by browsers.
https://github.com/vesoft-inc/nebula/blob/master/README-CN.md
image
image

I used the image path for architecture from English README as a replacement.
image

## What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

## How do you solve it?
Replace with the image path from English README.md
image

And now it can show the image.
image

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [x] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
Fixed image loading error for Chinese README.md

### CODE REVIEW

**Comment by Sophie-Xie** [comment]
Thanks for contribution. 
But I think we should change the image link from doc, @randomJoe211 pls check it.

**Comment by randomJoe211** [comment]
@TommyLemon Thanks! Please use this stable URL:
https://docs-cdn.nebula-graph.com.cn/figures/nebula-graph-architecture_3.png

**Comment by TommyLemon** [comment]
> @TommyLemon Thanks! Please use this stable URL: https://docs-cdn.nebula-graph.com.cn/figures/nebula-graph-architecture_3.png And please sign the CLA.
@randomJoe211 Hi, I've already changed the architecture image path with the url you gave me:
image

**Review by wey-gu — APPROVED** [review]
Thanks!

**Review by randomJoe211 — APPROVED** [review]

**Comment by Sophie-Xie** [comment]
@TommyLemon Thanks! pls sign the CLA, otherwise I can't merge.

image

image

**Comment by TommyLemon** [comment]
> @TommyLemon Thanks! pls sign the CLA, otherwise I can't merge.
> 
> image
> 
> image

@Sophie-Xie ok, I've already signed the CLA

**Pull request merged**
