### PR TITLE
Prune properties/no need to collect columns of dedup

### PR DESCRIPTION
**Pull request by jievince**
For vertex/edge, only vid/eid is used to dedup

### CODE REVIEW

**Comment by Shylock-Hg** [comment]
> For vertex/edge, only vid/eid is used to dedup

How about other cases?

**Comment by jievince** [comment]
> > For vertex/edge, only vid/eid is used to dedup
> 
> How about other cases?

we just prune properties of vertex and edge, so other data type of dedup is not affected

**Comment by Shylock-Hg** [comment]
> > > For vertex/edge, only vid/eid is used to dedup
> > 
> > 
> > How about other cases?
> 
> we just prune properties of vertex and edge, so other data type of dedup is not affected

How about this case, `match (v:player)-[:serve]->(t:team) with distinct v,t return t` ?

**Comment by jievince** [comment]
> > > > For vertex/edge, only vid/eid is used to dedup
> > > 
> > > 
> > > How about other cases?
> > 
> > 
> > we just prune properties of vertex and edge, so other data type of dedup is not affected
> 
> How about this case, `match (v:player)-[:serve]->(t:team) with distinct v,t return t` ?

PropertPruner will just prune the properties of vertex/edge. It will not prune the default properties such as "_id", "_src", "_dst". For your example, as long as the "_id" attribute of v and t vertices exists, there will be no correctness problems.

**Comment by Shylock-Hg** [comment]
> > > > > For vertex/edge, only vid/eid is used to dedup
> > > > 
> > > > 
> > > > How about other cases?
> > > 
> > > 
> > > we just prune properties of vertex and edge, so other data type of dedup is not affected
> > 
> > 
> > How about this case, `match (v:player)-[:serve]->(t:team) with distinct v,t return t` ?
> 
> PropertPruner will just prune the properties of vertex/edge. It will not prune the default properties such as "_id", "_src", "_dst". For your example, as long as the "_id" attribute of v and t vertices exists, there will be no correctness problems.

I have change this case, pls check it again.

**Comment by jievince** [comment]
> > > > > > For vertex/edge, only vid/eid is used to dedup
> > > > > 
> > > > > 
> > > > > How about other cases?
> > > > 
> > > > 
> > > > we just prune properties of vertex and edge, so other data type of dedup is not affected
> > > 
> > > 
> > > How about this case, `match (v:player)-[:serve]->(t:team) with distinct v,t return t` ?
> > 
> > 
> > PropertPruner will just prune the properties of vertex/edge. It will not prune the default properties such as "_id", "_src", "_dst". For your example, as long as the "_id" attribute of v and t vertices exists, there will be no correctness problems.
> 
> I have change this case, pls check it again.

It's still ok. After properties pruner, `v` only needs to fetch prop `_vid` and `age`, `t` needs to fetch all props.
So there is still no problem to do dedup.

**Comment by czpmango** [comment]
> > > > > > > For vertex/edge, only vid/eid is used to dedup
> > > > > > 
> > > > > > 
> > > > > > How about other cases?
> > > > > 
> > > > > 
> > > > > we just prune properties of vertex and edge, so other data type of dedup is not affected
> > > > 
> > > > 
> > > > How about this case, `match (v:player)-[:serve]->(t:team) with distinct v,t return t` ?
> > > 
> > > 
> > > PropertPruner will just prune the properties of vertex/edge. It will not prune the default properties such as "_id", "_src", "_dst". For your example, as long as the "_id" attribute of v and t vertices exists, there will be no correctness problems.
> > 
> > 
> > I have change this case, pls check it again.
> 
> It's still ok. After properties pruner, `v` only needs to fetch prop `_vid` and `age`, `t` needs to fetch all props. So there is still no problem to do dedup.

Please add test cases to verify correctness.

**Comment by czpmango** [comment]
> > > > For vertex/edge, only vid/eid is used to dedup
> > > 
> > > 
> > > How about other cases?
> > 
> > 
> > we just prune properties of vertex and edge, so other data type of dedup is not affected
> 
> How about this case, `match (v:player)-[:serve]->(t:team) with distinct v.age as age,t return t` ?

`v` is just not a property. `v` can be deduplicated according to `_vid`.
If `v` is required to carry some properties, the corresponding other plannodes(such as Project/Aggregate) must carry property expressions before the `dedup` plannode, because `distinct` can only appear in the with/return clause.

**Review by czpmango — APPROVED** [review]

**Comment by jievince** [comment]
> > > > > > > > For vertex/edge, only vid/eid is used to dedup
> > > > > > > 
> > > > > > > 
> > > > > > > How about other cases?
> > > > > > 
> > > > > > 
> > > > > > we just prune properties of vertex and edge, so other data type of dedup is not affected
> > > > > 
> > > > > 
> > > > > How about this case, `match (v:player)-[:serve]->(t:team) with distinct v,t return t` ?
> > > > 
> > > > 
> > > > PropertPruner will just prune the properties of vertex/edge. It will not prune the default properties such as "_id", "_src", "_dst". For your example, as long as the "_id" attribute of v and t vertices exists, there will be no correctness problems.
> > > 
> > > 
> > > I have change this case, pls check it again.
> > 
> > 
> > It's still ok. After properties pruner, `v` only needs to fetch prop `_vid` and `age`, `t` needs to fetch all props. So there is still no problem to do dedup.
> 
> Please add test cases to verify correctness.

Ok,  added.

**Review by czpmango — APPROVED** [review]

**Review by Shylock-Hg — APPROVED** [review]

**Pull request merged**
